### DISCUSSION TITLE
Has anyone gotten this working with gluetun?

### DISCUSSION THREAD

**Discussion by RagingFlames** [crazy-max/docker-rtorrent-rutorrent#450] [Q&A]
I'm trying to get this working with gluetun but am having trouble. When I go to the webui it says on the bottom right that port 50000 is closed, but I've passed that port to gluetun.

```
  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent-rutorrent
#    networks:
#      - rtorrent-rutorrent
#    expose:
#      - "${RT_DHT_PORT}/udp"
#      - "${XMLRPC_PORT}"
#      - "${RUTORRENT_PORT}"
#      - "${WEBDAV_PORT}"
#      - "${RT_INC_PORT}"
#    ports:
#      - target: ${RT_DHT_PORT}
#        published: ${RT_DHT_PORT}
#        protocol: udp
#      - target: ${RUTORRENT_PORT}
#        published: ${RUTORRENT_PORT}
#        protocol: tcp
#      - target: ${WEBDAV_PORT}
#        published: ${WEBDAV_PORT}
#        protocol: tcp
#      - target: ${RT_INC_PORT}
#        published: ${RT_INC_PORT}
#        protocol: tcp
    env_file:
      - "./rutorrent/rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "./rutorrent/data:/data"
      - "./rutorrent/downloads:/downloads"
      - "./rutorrent/passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    network_mode: "service:gluetun"
    restart: always

  rtorrent-logs:
    image: bash
    container_name: rtorrent-rutorrent-logs
    command: bash -c 'tail -f /log/*.log'
    network_mode: none
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "./rutorrent/data/rtorrent/log:/log"
    restart: always
#  network_mode: "service:gluetun"


############################
# GLUETUN
############################

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      # Other ports for other pods here
      - ${RT_DHT_PORT}:${RT_DHT_PORT} #rutorrent DHT UDP port (dht.port.set)
      - ${XMLRPC_PORT}:${XMLRPC_PORT} #rutorrent XMLRPC port through nginx over SCGI socket
      - ${RUTORRENT_PORT}:${RUTORRENT_PORT} #rutorrent webui
      - ${WEBDAV_PORT}:${WEBDAV_PORT} #rutorrent WebDAV port on completed downloads
      - ${RT_INC_PORT}:${RT_INC_PORT} #rutorrent Incoming connections (network.port_range.set)
```
