### DISCUSSION TITLE
Can't download faster than 1gbps with this image

### DISCUSSION THREAD

**Discussion by newadventure079** [crazy-max/docker-rtorrent-rutorrent#453] [Q&A]
I have internet that is 3gbps up and down. I have speedtested it and I really do get those speeds. I have a NAS with 64GB RAM with all SSDs. I have a 10gbps router and switch.

I was downloading some torrents that were heavily seeded yesterday. The speed increased steadily until it hit 125MB/s and then plateaued. This makes me think I got capped at 1gbps.

I tested a vanilla qbittorrent docker image with no performance improvements at all and I got around 433 MB/s download.

qbittorrent:
```
docker run -d \
    --name=qbittorrent \
    -e PUID=1026 \
    -e PGID=100 \
    -e WEBUI_PORT=8080 \
    -e TORRENTING_PORT=6882 \
    -p 8080:8080 \
    -p 6882:6882 \
    -p 6882:6882/udp \
    -v /volume2/docker/qbittorrent:/config \
    -v /volume1/NAS/Torrents:/downloads \
    --restart unless-stopped \
    lscr.io/linuxserver/qbittorrent:latest
```

.rtorrent.rc
```
# =========================
# Connection Settings
# =========================

# Set the max amount of memory address space used to mapping file chunks.
pieces.memory.max.set = 4096M

# Buffer sizes for sending data
network.send_buffer.size.set = 128M

# =========================
# Protocol Settings
# =========================

# Disable DHT (Distributed Hash Table) as using private trackers
dht.mode.set = disable

# Disable Peer Exchange (PEX)
protocol.pex.set = 0

# Encryption options
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# =========================
# System Settings
# =========================

# Set the umask for this process, which is applied to all files created by the program
system.umask.set = 0022

# Add a preferred filename encoding to the list
encoding.add = UTF-8

# =========================
# Directory and Session Management
# =========================

# Watch a directory for new torrents, and stop those that have been deleted
directory.watch.added = (cat,(cfg.watch)), load.start
schedule2 = untied_directory,5,5, (cat,"stop_untied=",(cfg.watch),"*.torrent")

# Close torrents when diskspace is low
schedule2 = monitor_diskspace,15,60,((close_low_diskspace,1000M))

# =========================
# Additional Settings
# =========================

network.xmlrpc.size_limit.set = 16M
trackers.delay_scrape = yes

# Save torrents immediately to prevent losing them between session saving intervals
method.set_key = event.download.inserted, 2_save_session, ((d.save_full_session))

# Configure session saving interval to balance disk usage and torrent information accuracy
schedule2 = session_save,1200,1200,((session.save))

#Start of my edits
check_hash = no
directory = /Torrents/temp
```

docker-compose:
```
version: "3.6"
services:
  rutorrent-Default:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "rutorrent-Default"
    entrypoint:
      - "/init"
    environment:
      - "RT_LOG_LEVEL=info"
      - "PUID=1026"
      - "OPCACHE_MEM_SIZE=64000"
      - "XMLRPC_SIZE_LIMIT=16M"
      - "MAX_FILE_UPLOADS=3000"
      - "XMLRPC_PORT=8000"
      - "TZ=America/Boise"
      - "PGID=100"
      - "UPLOAD_MAX_SIZE=1000M"
      - "RT_SEND_BUFFER_SIZE=64M"
      - "RU_REMOVE_CORE_PLUGINS=_cloudflare,_noty,_noty2,chunks,diskspace,cpuload,cookies,extratio,extsearch,feeds,filedrop,ipad,loginmgr,mediainfo,ratio,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,spectrogram,xmpp"
      - "RT_INC_PORT=50002"
      - "RT_SESSION_SAVE_SECONDS=1200"
      - "RT_RECEIVE_BUFFER_SIZE=64M"
      - "LOG_ACCESS=false"
      - "RT_TRACKER_DELAY_SCRAPE=true"
      - "RUTORRENT_PORT=9081"
      - "MEMORY_LIMIT=64000M"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PYTHONPATH=:/var/www/rutorrent"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_KILL_GRACETIME=10000"
    hostname: "rutorrent-Default"
    image: "crazymax/rtorrent-rutorrent:latest"
    ipc: "private"
    logging:
      driver: "db"
      options: {}
    networks:
      - "rutorrent"
    ports:
      - "50002:50002/tcp"
      - "6881:6881/udp"
      - "8000:8000/tcp"
      - "9000:9000/tcp"
      - "9081:9081/tcp"
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 32000
        hard: 40000
      nproc:
        soft: 65535
        hard: 65535
    volumes:
      - "/volume1/NAS/LTS:/LTS"
      - "/volume1/NAS/LTS:/volume1/NAS/LTS"
      - "/volume1/NAS/Plex:/Plex"
      - "/volume1/NAS/Torrents/Radarr:/Radarr"
      - "/volume1/NAS/Torrents/Sonarr:/Sonarr"
      - "/volume1/NAS/Torrents:/Torrents"
      - "/volume1/NAS/Torrents:/downloads"
    working_dir: "/"
networks:
  rutorrent:
    external: true
    name: "rutorrent"
```

Is this an underlying rtorrent issue?  qbit doesn't have this problem at all
