### ISSUE TITLE
Runing in microk8s 

### ISSUE THREAD

**Issue by docfactory37** [crazy-max/docker-rtorrent-rutorrent#114]
Hi All,

Just wanting some help i'm running this image in microk8s and when i deploy and start the container i get the below issue.

if i run it in just docker it works fine no issue.

I used to run this in microk8s but and to rebuild my server. hope some can help but its very odd as it used to work fine in the past.

![image](https://user-images.githubusercontent.com/20963053/128144515-95d392d1-c99d-45c7-8b26-2466cad3fee4.png)

**Comment by SeeTwoArrr** [comment]
Hi,

Not sure if this is still relevant but a lot will be needed than just a screenshot.

You said it's working on Docker, that makes me think it might be misconfiguration or incorrect yaml. What kind of resources are you deploying? Can you show the yaml?

**Comment by javydekoning** [comment]
Here is a working example with MetalLB:

````
apiVersion: v1
kind: Service
metadata:
  name: rutorrent
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: rutorrent
spec:
  selector:
    app: rutorrent
  type: LoadBalancer
  loadBalancerIP: 192.168.1.252
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: scgi
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: torrent-tcp
      port: 51413
      targetPort: 51413
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rutorrent-upd
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: rutorrent
spec:
  selector:
    app: rutorrent
  type: LoadBalancer
  loadBalancerIP: 192.168.1.252
  ports:
    - name: torrent-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
  namespace: default
  labels:
    app: rutorrent
spec:
  selector:
    matchLabels:
      app: rutorrent
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      containers:
        - name: rutorrent
          image: ghcr.io/crazy-max/rtorrent-rutorrent:4.0-0.9.8-0.13.8
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "4"
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: "911"
            - name: PGID
              value: "911"
            - name: RUTORRENT_PORT
              value: "8080"
            - name: RT_INC_PORT
              value: "51413"
            - name: XMLRPC_PORT
              value: "8000"
          ports:
            # RUTORRENT_PORT
            - containerPort: 8080
            # XMLRPC_PORT
            - containerPort: 8000
            # RT_INC_PORT
            - containerPort: 51413
            # DHT
            - containerPort: 6881
          volumeMounts:
            - name: downloads
              mountPath: /data/
              subPath: config/rtorrent-config
            - name: downloads
              mountPath: /downloads/
      volumes:
        - name: downloads
          hostPath:
            path: /downloads
            type: DirectoryOrCreate
      restartPolicy: Always
````
