### ISSUE TITLE
When I remove the torrent the data is also removed.

### ISSUE THREAD

**Issue by JC5** [crazy-max/docker-rtorrent-rutorrent#115]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I remove a torrent the data is also removed.

### Expected behaviour

The data remains.

### Actual behaviour

The data is deleted

### Steps to reproduce

1. Download torrent, wait for torrent to download.
2. Stop torrent so it is on "Finished"
3. Remove torrent. Do not select "remove and delete data"
4. All data from torrent in downloads/complete is gone.

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 50
  Running: 48
  Paused: 0
  Stopped: 2
 Images: 159
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-80-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
 Name: highgarden
 ID: IDXE:GNJX:VWBV:QG7S:XIZO:H46F:VITL:NCEO:LYLT:JSP6:F2QJ:WHPL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
```


### Version

* `docker-compose version 1.25.0, build unknown`
* `Linux highgarden 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`


### Docker compose

```yaml
services:
  rutorrent:
    container_name: rutorrent
    environment:
      MAX_FILE_UPLOADS: '3'
      PGID: '1000'
      PUID: '1000'
      RT_INC_PORT: '51413'
      TZ: Europe/Amsterdam
      WAN_IP: 84.83.118.219
    image: crazymax/rtorrent-rutorrent
    ports:
    - 10016:8080/tcp
    - 5000:5000/tcp
    - 51413:51413/tcp
    - 6881:6881/udp
    restart: unless-stopped
    volumes:
    - /home/me/docker-volumes/rutorrent-config:/data:rw
    - /media/norvos/me/downloads:/downloads:rw
version: '2.1'
```
```


### Container logs

No logs

### Additional info

_No response_
