### ISSUE TITLE
rtorrent.lock not removed when container is stopped

### ISSUE THREAD

**Issue by jeff47** [crazy-max/docker-rtorrent-rutorrent#123]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am running into a problem:  When stopping the container (`docker-compose stop rutorrent`), the lock file in /session is left behind.  This prevents the container from restarting, and can be confusing to users who don't know how to check the log.

This appears to be related to the time required for rtorrent to shutdown when there are a large number of torrents (my client has > 2500 seeding).  Docker and docker-compose allow 10 seconds to elapse after the SIGTERM signal is sent before it sends SIGKILL, which doesn't give rtorrent enough time to gracefully close if there are a lot of torrents.  In cases where a lot of torrents are being seeded, rTorrent gets killed and the lockfile isn't removed.

This can be resolved by allowing a longer timeout for shutdown, either by adding a stop_grace_period to the docker-compose.yml file, or adding the `-t XX` parameter to the `docker stop` or `docker-compose stop` commands.

### Expected behaviour

rTorrent should remove lockfile after container is stopped. 

### Actual behaviour

The lockfile persists after container is stopped.

### Steps to reproduce

1.  docker-compose up -d rutorrent
2. docker-compose stop rutorrent

### Docker info

```yaml
Client:
 Debug Mode: false

Server:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 37
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.6.17-050617-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 Name: bunkerhill
 ID: XNA7:AVQ6:73XC:NGTK:ELFZ:TDE2:LVIV:J7D2:2AW5:XKKK:A2YY:C6MH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Version

* Docker compose version (type `docker-compose --version`):  **docker-compose version 1.29.2, build 5becea4c**
* System info (type `uname -a`): **Linux xxx 5.6.17-050617-generic #202006071230 SMP Sun Jun 7 12:35:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**

### Docker compose

My docker-compose.yml is long and complicated, and I don't think it's relevant to the issue here.  Happy to provide it if needed.

```yaml
n/a
```

### Container logs

n/a

### Additional info

This is something to consider adding to the docs and the command examples, and might reduce some issues people having with the container not starting because it finds a stale lock file.

It's also possible that a way for the startup script to check for and remove a stale lockfile would be helpful, but I think giving rTorrent sufficient time for a graceful shutdown is preferable!
