### ISSUE TITLE
Can't run on Raspberry Pi 3 with Raspberry Pi OS 2021-05-07

### ISSUE THREAD

**Issue by abouroubi** [crazy-max/docker-rtorrent-rutorrent#126]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm not able to run the image in a raspberry pi with Raspberry Pi OS.

### Expected behaviour

The image should run on raspberry pi.

### Actual behaviour

When I try to start the defaul docker-compose I have this error:
```
rtorrent-rutorrent    | /bin/sh: can't access tty; job control turned off
rtorrent-rutorrent    | /run/s6/services # 
rtorrent-rutorrent    | s6-svscan: warning: unable to iopause: Operation not permitted
rtorrent-rutorrent    | s6-svscan: warning: executing into .s6-svscan/crash
rtorrent-rutorrent    | s6-svscan panicked! Dropping to a root shell.
rtorrent-rutorrent    | 
rtorrent-rutorrent    | /bin/sh: can't access tty; job control turned off
rtorrent-rutorrent    | /run/s6/services # 
```

### Steps to reproduce

1. Copy the content of `docker-rtorrent-rutorrent/examples/compose/` to a Raspberry Pi 3
2. run `suod docker-copose up`

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.63-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: raspberrypi
 ID: 44A4:WIUR:43BO:NKXV:MJ2I:P6RB:JKGA:4UFK:GK4V:ILUB:4YBG:OBOH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Version

* Docker compose version (type `docker-compose --version`): docker-compose version 1.29.2, build unknown
* System info (type `uname -a`): Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

### Docker compose

```yaml
services:
  rtorrent-logs:
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      rtorrent-rutorrent:
        condition: service_started
    image: bash
    restart: always
    volumes:
    - /home/pi/torrent/data/rtorrent/log:/log:rw
  rtorrent-rutorrent:
    container_name: rtorrent-rutorrent
    environment:
      AUTH_DELAY: 0s
      LOG_IP_VAR: remote_addr
      MAX_FILE_UPLOADS: '50'
      MEMORY_LIMIT: 256M
      OPCACHE_MEM_SIZE: '128'
      PGID: '1000'
      PUID: '1000'
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      RT_LOG_EXECUTE: "false"
      RT_LOG_LEVEL: info
      RT_LOG_XMLRPC: "false"
      RUTORRENT_AUTHBASIC_STRING: ruTorrent restricted access
      RUTORRENT_PORT: 8090
      RU_DO_DIAGNOSTIC: "true"
      RU_FORBID_USER_SETTINGS: "false"
      RU_HTTP_TIME_OUT: '30'
      RU_HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101
        Firefox/12.0
      RU_HTTP_USE_GZIP: "true"
      RU_LOCALE: UTF8
      RU_LOG_FILE: /data/rutorrent/rutorrent.log
      RU_LOG_RPC_CALLS: "false"
      RU_LOG_RPC_FAULTS: "true"
      RU_OVERWRITE_UPLOADED_TORRENTS: "false"
      RU_PHP_GZIP_LEVEL: '2'
      RU_PHP_USE_GZIP: "false"
      RU_REMOVE_CORE_PLUGINS: erasedata,httprpc
      RU_RPC_TIME_OUT: '5'
      RU_SAVE_UPLOADED_TORRENTS: "true"
      RU_SCHEDULE_RAND: '10'
      TZ: Europe/Paris
      UPLOAD_MAX_SIZE: 16M
      WEBDAV_AUTHBASIC_STRING: WebDAV restricted access
      XMLRPC_AUTHBASIC_STRING: rTorrent XMLRPC restricted access
    expose:
    - 6881/udp
    - '8000'
    - '8090'
    - '9000'
    - '50000'
    image: crazymax/rtorrent-rutorrent:latest
    ports:
    - protocol: udp
      published: 6881
      target: 6881
    - protocol: tcp
      published: 8090
      target: 8090
    - protocol: tcp
      published: 9000
      target: 9000
    - protocol: tcp
      published: 50000
      target: 50000
    restart: always
    ulimits:
      nofile:
        hard: 40000
        soft: 32000
      nproc: 65535
    volumes:
    - /home/pi/torrent/data:/data:rw
    - /home/pi/torrent/downloads:/downloads:rw
    - /home/pi/torrent/passwd:/passwd:rw
version: '3'
```

### Container logs

```
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-logs_1       | tail: can't open '/log/*.log': No such file or directory
rtorrent-logs_1       | tail: no files
rtorrent-rutorrent    | s6-svscan: warning: unable to iopause: Operation not permitted
rtorrent-rutorrent    | s6-svscan: warning: executing into .s6-svscan/crash
rtorrent-rutorrent    | s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted
rtorrent-rutorrent    | s6-svscan panicked! Dropping to a root shell.
rtorrent-rutorrent    | 
rtorrent-rutorrent    | /bin/sh: can't access tty; job control turned off
rtorrent-rutorrent    | /run/s6/services #
rtorrent-rutorrent exited with code 0
```
