### ISSUE TITLE
Do not require external internet connectivity and/or WAN_IP to be defined during start-up

### ISSUE THREAD

**Issue by lps-rocks** [crazy-max/docker-rtorrent-rutorrent#130]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Requiring working DNS to an external DNS provider andor a defined WAN_IP is not necessary during start-up. There's also no reason to force rTorrent to use an external IP for announcements. If omitted, any tracker's announce will use the IP the connection is made from, most trackers actually ignore any explicitly reported IP by the client to prevent reflection attacks. 

Futhermore, requiring a working internet connection to start-up is bad practice when WAN_IP is not defined. It's also bad practice to require an external DNS service on start up to resolve the external IP. This can cause unnecessary flooding and abuse of the target DNS server if rTorrent gets caught in a start up loop. 

### Expected behaviour

rTorrent should start up without a defined WAN_IP or external DNS being functional.

### Actual behaviour

rTorrent fails to start without a defined WAN_IP when external DNS is not availab.e 

### Steps to reproduce

1. Deploy container without external internet connection or WAN_IP defined
2. Watch rTorrent fail to start rapidly due to invalid command line caused by the start-up script injecting a timeout result from 'dig' into the command line.

### Docker info

```yaml
:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 1.4.5~ds1-2
 runc version: 1.0.0~rc93+ds1-5+b2
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.10.0-8-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 28
 Total Memory: 62.69GiB
 Name: server
 ID: 44X4:CUOE:OG4C:IX6Q:G5G5:LVQB:VUIG:FUW5:B7F3:F36E:ZOYD:HDDQ
 Docker Root Dir: /mnt/nvme_raid10/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* ```udocker-compose version 1.25.0, build unknown```
* ```Linux server 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux```

### Docker compose

```yaml
N/A
```

### Container logs

N/A
