### ISSUE TITLE
High memory usage?

### ISSUE THREAD

**Issue by ghost** [crazy-max/docker-rtorrent-rutorrent#137]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,
just installed to my docker (portainer). Have 1 torrent there (14GB) but ruTorrent uses 14.9GB of memory now.
Any fix please?

### Expected behaviour

...

### Actual behaviour

...

### Steps to reproduce

...

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)
```

### Version

Docker Compose version v2.1.1

Linux server 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### Docker compose

```yaml
version: "3"
services:
  rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - RUTORRENT_PORT=80
      - RT_INC_PORT=51250
      - RU_REMOVE_CORE_PLUGINS=httprpc,_cloudflare,_noty,_noty2,cookies,extratio,extsearch,feeds,filedrop,history,loginmgr,lookat,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,show_peers_like_wtorrent,spectrogram,trafic,unpack,uploadeta,xmpp
    volumes:
      - /home/docker/data/rutorrent/data:/data
      - /home/docker/data/rutorrent/downloads:/downloads
      - /home/docker/data/rutorrent/passwd:/passwd
    ports:
      - 80:80
      - 5000:5000
      - 50000:50000
      - 6881:6881/udp
```

### Container logs

...
