### ISSUE TITLE
Docker - Portainer - rTorrent restarting?

### ISSUE THREAD

**Issue by USRGH** [crazy-max/docker-rtorrent-rutorrent#139]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,
my rTorrent/ruTorrent is randomly restarting. Today I removed 3 torrents from client and ruTorrent restarted. I see it because of 0 DL/UL data now.
Any idea what is wrong please?

Here is my composer-data:
> version: "3"
> services:
>   rutorrent:
>     image: crazymax/rtorrent-rutorrent:latest
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - RUTORRENT_PORT=80
>       - RT_INC_PORT=xxxx
>       - RU_REMOVE_CORE_PLUGINS=httprpc,_cloudflare,_noty,_noty2,cookies,extratio,extsearch,feeds,filedrop,history,loginmgr,lookat,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,show_peers_like_wtorrent,spectrogram,trafic,unpack,uploadeta,xmpp
>     volumes:
>       - /home/user/data/rutorrent/data:/data
>       - /home/user/data/rutorrent/downloads:/downloads
>       - /home/user/data/rutorrent/passwd:/passwd
>     ports:
>       - xxxx:80
>       - 5000:5000
>       - xxxx:xxxx
>       - 6881:6881/udp

Didn't find anything in rutorrent/data/rtorrent/log
> 1640882711 N rtorrent main: Starting thread.
> 1640882711 N rtorrent scgi: Starting thread.

### Expected behaviour

-

### Actual behaviour

removing 3 torrents from ruTorrent

### Steps to reproduce

-

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 13
  Running: 9
  Paused: 0
  Stopped: 4
 Images: 38
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: lpz93zb4y2uti4jz1ows06fuw
  Is Manager: true
  ClusterID: kc5qoyenccsezir8o8mxnhfux
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 1.2.3.4
  Manager Addresses:
   1.2.3.4:2377
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-9-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: home.rtd.sk
 ID: EPLJ:UGZN:5AI7:Q7PP:QYEU:VJW7:UVV4:JRSH:LP2N:EWGZ:JVJA:3PFN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

Docker Compose version v2.1.1
Linux mydomain.com 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### Docker compose

```yaml
can't find a suitable configuration file in this directory or any parent: not found
```

### Container logs

-
