### ISSUE TITLE
Entire Docker environment freezes using vanilla compose

### ISSUE THREAD

**Issue by fredrikscode** [crazy-max/docker-rtorrent-rutorrent#143]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Running your compose example results in Docker not responding to any commands.

### Expected behaviour

rTorrent and ruTorrent up and running using compose + env-files from https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/compose

### Actual behaviour

The logs container did not come up for a few minutes and here Docker stopped responding to any command. ruTorrent was available through the webui.

### Steps to reproduce

- Copy all files from https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/compose into the same folder
- Run docker-compose up -d

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: loki
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 Name: portainer
 ID: DXOE:37YE:C5ZB:NNZC:6UFT:ICQS:U6E5:455B:VVTQ:CPDC:WHO2:IZLN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

- Linux portainer 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
- Docker version 20.10.12, build e91ed57
- docker-compose version 1.29.2, build 5becea4c

### Docker compose

```yaml
version: "3.2"

services:
  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - "./data/geoip:/data"
    env_file:
      - "./geoip-updater.env"
    restart: always

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "./data/rtorrent/log:/log"
    restart: always
```

### Container logs

Unable to fetch logs (docker commands not responding) before containers were removed.

### Additional info

**Troubleshooting (docker commands not available..):**
- systemctl restart docker, no response.
- Killed the PID of the containers, issue persisted.
- Rebooting the host, issue persisted.
- Removing containers created from your compose from /var/lib/docker/containers did wake Docker up.

I had the same issue before mentioning above, the only different thing I did then was changing a few ports. I don't know what logs to provide that would be beneficial. Going to try and get it into Portainer instead and see if that works better.
