### ISSUE TITLE
HTTP auth with SWAG

### ISSUE THREAD

**Issue by Al4ndil** [crazy-max/docker-rtorrent-rutorrent#147]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I can't use http auth with SWAG.
I tried HTTP authentication on rutorrent. It works fine if I connect live to my machine via the IP address.
I tried HTTP authentification on SWAG without HTTP auth on rutorrent. It doesn't work.
I tried HTTP authentification on SWAG with HTTP auth on rutorrent. It doesn't work.
I tried HTTP authentication on SWAG with or without HTTP auth on rutorrent and having changed LOG_IP_VAR=http_x_forwarded_for as for env variables for traefik. It does not work. ERROR 403

### Expected behaviour

I would like use to HTTP authentification  with SWAG.

### Actual behaviour

Description

### Steps to reproduce

 Description

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.3.0)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: XXXX
 ID: XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
Docker Compose version v2.3.0
Linux XXXX 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

### Docker compose

```yaml
version: "3.2"
services:
    rtorrent-rutorrent:
        image: crazymax/rtorrent-rutorrent:latest
        container_name: rutorrent
        # ###############
        labels:
        # Le label ci-dessous permet à Watchtower de faire les mises à jour automatiquement
        # Cela peut être supprimé si Watchtower n'est pas utilisé.
            - com.centurylinklabs.watchtower.enable=true
        # Le label ci-dessous permet à Autoheal de redémarrer automatiquement le conteneur
        # Cela peut être supprimé si Autoheal n'est pas utilisé.
            - autoheal=true
        # ###############
        #depends_on:
        #  - vpn
        # ###############
        networks:
            default:
        # Définition de l'adresse IP du conteneur à l'intérieur du bridge
                ipv4_address: 172.30.0.2
        # ###############
        ports :
        # Définition des ports externe:interne utilisés par le conteneur
            - 6881:6881/udp
            - 7000:8000
            - 9080:8080
            - 10000:9000
            - 50000:50000
        # ###############
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - AUTH_DELAY=0s
            - MEMORY_LIMIT=256M
            - UPLOAD_MAX_SIZE=16M
            - OPCACHE_MEM_SIZE=128
            - MAX_FILE_UPLOADS=50
            - REAL_IP_FROM=0.0.0.0/32
            - REAL_IP_HEADER=X-Forwarded-For
            - LOG_IP_VAR=http_x_forwarded_for #remote_addr
            - XMLRPC_AUTHBASIC_STRING=rTorrent XMLRPC restricted access
            - RUTORRENT_AUTHBASIC_STRING=ruTorrent restricted access
            - WEBDAV_AUTHBASIC_STRING=WebDAV restricted access
            - RT_LOG_LEVEL=info
            - RT_LOG_EXECUTE=false
            - RT_LOG_XMLRPC=false
            - RU_REMOVE_CORE_PLUGINS=erasedata,httprpc,geoip,geoip2
            - RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
            - RU_HTTP_TIME_OUT=30
            - RU_HTTP_USE_GZIP=true
            - RU_RPC_TIME_OUT=5
            - RU_LOG_RPC_CALLS=false
            - RU_LOG_RPC_FAULTS=true
            - RU_PHP_USE_GZIP=false
            - RU_PHP_GZIP_LEVEL=2
            - RU_SCHEDULE_RAND=10
            - RU_LOG_FILE=/data/rutorrent/rutorrent.log
            - RU_DO_DIAGNOSTIC=true
            - RU_SAVE_UPLOADED_TORRENTS=true
            - RU_OVERWRITE_UPLOADED_TORRENTS=false
            - RU_FORBID_USER_SETTINGS=false
            - RU_LOCALE=UTF8
        # ###############
        #network_mode: "service:vpn"
        # ###############
        volumes:
            - ${RACINE_CONF_CONTENEURS}/rutorrent/config:/data
            - ${RACINE_DOWNLOADS}:/downloads
            - ${RACINE_TMP}:/TMP
            - ${RACINE_CONF_CONTENEURS}/rutorrent/passwd:/passwd
        # ###############
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
        # ###############
        restart: unless-stopped
        # ###############
```

### Container logs

Log level=info
