### ISSUE TITLE
"Unpack plugin: rTorrent user can't access 'unrar' program" after upgrading to 3.10-0.9.8-0.13.8-r18 or later

### ISSUE THREAD

**Issue by jnsn** [crazy-max/docker-rtorrent-rutorrent#160]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating to the latest version, the unpack plugin is logging the following error:

```
Unpack plugin: rTorrent user can't access 'unrar' program.
```

The `unrar` utility was removed by https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/151, but there doesn't seem to be a mention as to why.

### Expected behaviour

`unrar` should be installed.

### Actual behaviour

`unrar` is not installed and the Unpack plugin will log an error message.

### Steps to reproduce

1. Install or upgrade to [3.10-0.9.8-0.13.8-r18](https://github.com/crazy-max/docker-rtorrent-rutorrent/releases/tag/3.10-0.9.8-0.13.8-r18)

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 26
  Running: 26
  Paused: 0
  Stopped: 0
 Images: 135
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-109-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.36GiB
 Name: [REDACTED]
 ID: MVL7:VJMI:N2EG:4TUN:PVYL:MSZB:HRAZ:K7OM:C6NS:NFE6:TADL:HAOQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Version

* docker-compose version 1.29.2, build 5becea4c
* Linux [REDACTED] 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
/
```

### Container logs

/
