### ISSUE TITLE
Port conflicts in reverse proxy

### ISSUE THREAD

**Issue by fredrikscode** [crazy-max/docker-rtorrent-rutorrent#169]
Hi,

I appreciate this image but I have an issue I can't figure out. I have port conflicts and need to change ports used in this container however I can't for the life of me get my changes through.

This container is connected to a VPN container via network_mode where other services have conflicting ports which I cannot change.

As far as I've tested, the provided .env file to the compose doesn't affect XMLRPC_PORT (tested with network_mode: host as well). It still tries to bind to 8000. RT_INC_PORT can be modified though..

**.env**
```
RT_DHT_PORT=6881
XMLRPC_PORT=8001
RUTORRENT_PORT=8081
WEBDAV_PORT=9001
RT_INC_PORT=55000
```

**compose.yml**
```
version: "3"
services:

  rtorrent:
    container_name: rtorrent
    image: crazymax/rtorrent-rutorrent:latest
    restart: unless-stopped
    network_mode: "container:vpn"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "./data:/data"
      - "/mnt/media/:/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    stop_grace_period: "20s"
```

Do I need to modify the Dockerfile to get this to work? I've looked at it and couldn't figure out where to change the default ports. Any help is highly appreciated :)
