### ISSUE TITLE
Drag-and-drop torrents limited to 2mb

### ISSUE THREAD

**Issue by treyturner** [crazy-max/docker-rtorrent-rutorrent#173]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm a new user working with a fresh instance. I'm finding that the max torrent upload size is 2 MB regardless of whether `UPLOAD_MAX_SIZE` is set.

### Expected behaviour

The max upload size is 16M by default. I can change it by setting the `UPLOAD_MAX_SIZE` environment variable.

### Actual behaviour

The max upload size is 2 MB regardless of whether I set `UPLOAD_MAX_SIZE` to another value or don't set it at all.

### Steps to reproduce

1. Create a fresh instance of the app using the `latest` image (`7ca3edf2e101`).
2. Drag a torrent greater than 2 MB into the application window.
3. See the error toast and the following error logged:
```
Redacted.torrent is too large. Please upload files up to 2MiB
```

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 36
 Server Version: 20.10.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.28-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.81GiB
 Name: vault
 ID: RUJA:NBQW:XAZF:ISG3:TINP:VVRD:VG3P:HM3G:DQ7U:ALLY:TTTO:5MBQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Version

* Docker compose version (type `docker-compose --version`):
This is running inside portainer which has no shell, so I can't easily tell the version. I'll keep working on it though.
* System info (type `uname -a`):
`Linux vault 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux`

### Docker compose

```yaml
version: "3.2"

services:
  rtorrent:
    image: crazymax/rtorrent-rutorrent
    container_name: rtorrent
    ports:
      - "5001:5001"
      - "6882:6882/udp"
      - "8803:8803"
      - "51414:51414"
      - "9009:9009"
    environment:
      - TZ=US/Central
      - PUID=1000
      - PGID=100
      - WAN_IP_CMD=false
      - AUTH_DELAY=0s
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - MAX_FILE_UPLOADS=50
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - LOG_ACCESS=true
      - LOG_LEVEL=debug
      - XMLRPC_AUTHBASIC_STRING=rTorrent XMLRPC restricted access
      - RUTORRENT_AUTHBASIC_STRING=ruTorrent restricted access
      - WEBDAV_AUTHBASIC_STRING=WebDAV restricted access
      - RT_LOG_LEVEL=info
      - RT_LOG_EXECUTE=false
      - RT_LOG_XMLRPC=false
      - RU_REMOVE_CORE_PLUGINS=erasedata,httprpc
      - RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
      - RU_HTTP_TIME_OUT=30
      - RU_HTTP_USE_GZIP=true
      - RU_RPC_TIME_OUT=5
      - RU_LOG_RPC_CALLS=false
      - RU_LOG_RPC_FAULTS=true
      - RU_PHP_USE_GZIP=false
      - RU_PHP_GZIP_LEVEL=2
      - RU_SCHEDULE_RAND=10
      - RU_LOG_FILE=/data/rutorrent/rutorrent.log
      - RU_DO_DIAGNOSTIC=true
      - RU_SAVE_UPLOADED_TORRENTS=true
      - RU_OVERWRITE_UPLOADED_TORRENTS=false
      - RU_FORBID_USER_SETTINGS=false
      - RU_LOCALE=UTF8
      - RT_DHT_PORT=6882
      - XMLRPC_PORT=5001
      - RUTORRENT_PORT=8803
      - WEBDAV_PORT=9009
      - RT_INC_PORT=51414
    volumes:
      - config:/data
      - /mnt/user/downloads/Torrents:/downloads/complete
      - /mnt/user/incomplete-downloads/:/downloads/temp
      - passwd:/passwd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped
  
volumes:
  config:
  passwd:
```

### Container logs

Nothing is logged about the attempt, so I simply have these lines repeating in the logs, even with LOG_LEVEL set to `debug`:
```
192.168.1.1 - browse [22/May/2022:21:28:19 -0500] "POST /plugins/rpc/rpc.php HTTP/1.1" 200 1761 "http://redacted:8803/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
192.168.1.1 - browse [22/May/2022:21:28:19 -0500] "POST /plugins/rpc/rpc.php HTTP/1.1" 200 473 "http://redacted:8803/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
192.168.1.1 - browse [22/May/2022:21:28:19 -0500] "GET /plugins/cpuload/action.php?_=1653272881233 HTTP/1.1" 200 13 "http://redacted:8803/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
```

### Additional info

I checked the PHP configs and found that `/etc/php7/php-fpm.d/www.conf` has these values set:
```
php_admin_value[post_max_size] = 16M
php_admin_value[upload_max_filesize] = 16M
```
which I expected based on the commands in `rootfs/etc/cont-init.d/03-config.sh`. I also noticed this line in `/etc/php7/php.ini`:
```
upload_max_filesize = 2M
```
which I guess is also expected, since `03-config.sh` makes no attempt to edit it. Just to be sure, I changed this value to `16M` and restarted the container (without removing it, so as to persist the change), but I still get the toast and error when trying to drag and drop the 2.6 MB torrent.

Just curious what else I might be doing wrong here since no one else seems to be experiencing this issue. Thanks for your time and work on this image.
