### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by ufo56** [crazy-max/docker-rtorrent-rutorrent#187]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi

I don't know for how long but now I discovered that rtorrent is eating all available memory on host system when downloading a torrent(because i had do download bigger torrents than usual ~10gb). I had to limit 8gb on docker, otherwise whole system basically crash...., after it hits 8gb limit it crashes and starts again. There is no difference if i use edge version or latest.

Short gif where you can see how memory usage increases https://i.imgur.com/f9C5Yz0.gif

250 torrents are seeding and about 15 from these are 200-300gb.

### Expected behaviour

Not to eat all memory ?

### Actual behaviour

When downloading a torrent, docker container start using high amount of memory.

### Steps to reproduce

Download a torrent?

### Docker info

```yaml
# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 63
  Running: 41
  Paused: 0
  Stopped: 22
 Images: 65
 Server Version: 20.10.18
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                          yslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.19.14-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.4GiB
 Name: Tower
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Version

# uname -a
Linux Tower 5.19.14-Unraid #1 SMP PREEMPT_DYNAMIC Thu Oct 6 09:15:00 PDT 2022 x86_64 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz GenuineIntel GNU/Linux

### Docker compose

```yaml
docker run
  -d
  --name='rtorrent-rutorrent'
  --net='bridge'
  -e TZ="Europe/Kiev"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="rtorrent-rutorrent"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8042]'
  -l net.unraid.docker.icon='/plugins/dynamix.docker.manager/images/question.png'
  -p '8042:8080/tcp'
  -p '6881:6881/udp'
  -p '51413:51413/tcp'
  -p '8043:8000/tcp'
  -v '/mnt/user/appdata/rutorrent/':'/data':'rw'
  -v '/mnt/user/torrent/':'/downloads':'rw'
  -v '/mnt/user/appdata/flood/socket/':'/var/run/rtorrent/':'rw,shared'
  -e "RT_LOG_LEVEL=error"
  -e "RU_LOG_FILE=/data/rutorrent/rutorrent.log"
  -e "TZ=Europe/Helsinki"
  -e "MEMORY_LIMIT=512M"
  -e "UPLOAD_MAX_SIZE=32M"
  -e "OPCACHE_MEM_SIZE=128"
  -e "MAX_FILE_UPLOADS=50"
  -e "REAL_IP_FROM=0.0.0.0/32"
  -e "REAL_IP_HEADER=X-Forwarded-For"
  -e "LOG_IP_VAR=remote_addr"
  -e "RT_LOG_EXECUTE=false"
  -e "RT_LOG_XMLRPC=false"
  -e "RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0 "
  -e "RU_HTTP_TIME_OUT=60"
  -e "RU_HTTP_USE_GZIP=true"
  -e "RU_RPC_TIME_OUT=10"
  -e "RU_LOG_RPC_CALLS=false"
  -e "RU_LOG_RPC_FAULTS=true"
  -e "RU_PHP_USE_GZIP=false"
  -e "RU_PHP_GZIP_LEVEL=2"
  -e "RU_SCHEDULE_RAND=10"
  -e "RU_DO_DIAGNOSTIC=true"
  -e "RU_SAVE_UPLOADED_TORRENTS=true"
  -e "RU_OVERWRITE_UPLOADED_TORRENTS=false"
  -e "RU_FORBID_USER_SETTINGS=false"
  -e "RU_LOCALE=UTF8"
  --log-opt max-size=50m
  --log-opt max-file=1
  --memory=8G 'crazymax/rtorrent-rutorrent:edge'
```

### Container logs

Log_level=debug 
makes a enormous file

### Additional info

```yaml
throttle.global_down.max_rate.set = 0
throttle.global_up.max_rate.set = 0
throttle.max_peers.normal.set = 100
throttle.max_peers.seed.set = -1
throttle.max_uploads.set = 100
throttle.min_peers.normal.set = 1
throttle.min_peers.seed.set = -1

pieces.memory.max.set = 2000M

network.max_open_files.set = 10000

# XMLRPC size limit
network.xmlrpc.size_limit.set = 8M

#scgi_port = 127.0.0.1:5000

# Enable DHT support for trackerless torrents or when all trackers are down
# May be set to "disable" (completely disable DHT), "off" (do not start DHT),
# "auto" (start and stop DHT as needed), or "on" (start DHT immediately)
dht.mode.set = auto

# Enable peer exchange (for torrents not marked private)
protocol.pex.set = yes

# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported
pieces.hash.on_completion.set = no

# Set whether the client should try to connect to UDP trackers
#trackers.use_udp.set = yes

# Set the max amount of memory address space used to mapping file chunks. This refers to memory mapping, not
# physical memory allocation. Default: 1GB (max_memory_usage)
# This may also be set using ulimit -m where 3/4 will be allocated to file chunks
#pieces.memory.max.set = 1GB

# Alternative calls to bind and ip that should handle dynamic ip's
#schedule2 = ip_tick,0,1800,ip=rakshasa
#schedule2 = bind_tick,0,1800,bind=rakshasa

# Encryption options, set to none (default) or any combination of the following:
# allow_incoming, try_outgoing, require, require_RC4, enable_retry, prefer_plaintext
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Set the umask for this process, which is applied to all files created by the program
system.umask.set = 0022

# Add a preferred filename encoding to the list
encoding.add = UTF-8

# Watch a directory for new torrents, and stop those that have been deleted
#schedule2 = watch_directory, 1, 1, (cat,"load.start=",(cfg.watch),"*.torrent")
#schedule2 = untied_directory, 5, 5, (cat,"stop_untied=",(cfg.watch),"*.torrent")

# Close torrents when diskspace is low
schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace,1000M))

# Move finished (no need Autotools/Automove plugin on ruTorrent)
#method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
#method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
#method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="

# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
#method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="

#bind = 0.0.0.0
port_range = 51413-51413
check_hash = no
encryption = allow_incoming,try_outgoing,enable_retry
dht = off
dht_port = 6881
directory = /downloads/
upload_rate = 0
download_rate = 41000
```
