### ISSUE TITLE
Traefik config not working as intended

### ISSUE THREAD

**Issue by alaakaazaam** [crazy-max/docker-rtorrent-rutorrent#206]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

By runnin docker-compose up -d from this example (https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/traefik), i encouter this error each time : 

ERROR: for traefik Cannot start service traefik: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init 

 

### Expected behaviour

the container should start and activate https routes smoothly

### Actual behaviour

The container never starts properly

### Steps to reproduce

A- Git clone https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/traefik
B- Follow Readme instructions
C- Run docker-compose up -d

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 13
  Running: 4
  Paused: 0
  Stopped: 9
 Images: 39
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-18-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.67GiB
 Name: vmi208991
 ID: DULK:BUZX:CXVR:EY7U:JBTW:PKR2:7GHC:E352:MV62:ARTB:PUVT:4HJX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
Linux vmi208991 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
docker-compose version 1.25.3, build d4d1b42b

### Docker compose

```yaml
version: "3.2"

services:
  traefik:
    image: traefik:2.5
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=webmaster@example.com"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/acme/acme.json
    volumes:
      - "./acme:/acme"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - "./data/geoip:/data"
    env_file:
      - "./geoip-updater.env"
    restart: always

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
      - "./passwd:/passwd"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rutorrent.entrypoints=https"
      - "traefik.http.routers.rutorrent.rule=Host(`www.xxx.yyy.zzz`)"
      - "traefik.http.routers.rutorrent.tls=true"
      - "traefik.http.routers.rutorrent.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rutorrent.tls.domains[0].main=www.xxx.yyy.zzz"
      - "traefik.http.routers.rutorrent.service=rutorrent"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=${RUTORRENT_PORT}"
      - "traefik.http.routers.webdav.entrypoints=https"
      - "traefik.http.routers.webdav.rule=Host(`www.xxx.yyy.zzz`)"
      - "traefik.http.routers.webdav.tls=true"
      - "traefik.http.routers.webdav.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webdav.tls.domains[0].main=www.xxx.yyy.zzz"
      - "traefik.http.routers.webdav.service=webdav"
      - "traefik.http.services.webdav.loadbalancer.server.port=${WEBDAV_PORT}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "./data/rtorrent/log:/log"
    restart: always
```

### Container logs

No log available, sorry
