### ISSUE TITLE
"Call is not valid XML" for every XMLRPC request

### ISSUE THREAD

**Issue by logical-and** [crazy-max/docker-rtorrent-rutorrent#212]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

First of all - thank you for you hard works, and this brilliant docker build.

The setup does not work in Transmission Remote Android app, although it worked when I set rTorrent manually (with no docker). 

I see (by logs) it can connect to XMLFPS, but it looks like either nginx converts http to fcgi poorly or fcgi reads request with errors. But anyways it returns the following error:

`Call is not valid XML.  not well-formed`

Please see details

![](https://i.imgur.com/qZmPxho.png)
![](https://i.imgur.com/w4FnWlz.png)

My settings are completely based on your [composer example](https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/compose), with few changes:

```
rtorrent-rutorrent.env:

RT_LOG_LEVEL=debug
RT_LOG_XMLRPC=true
```

```
docker-compose.yml:

services:
  rtorrent-rutorrent:
    ports:
      - target: ${XMLRPC_PORT}
        published: ${XMLRPC_PORT}
        protocol: tcp
```

This is from rTorrent logs:

```text
^@492:CONTENT_LENGTH^@344^@REQUEST_METHOD^@POST^@REQUEST_URI^@/transmission/rpc^@QUERY_STRING^@^@CONTENT_TYPE^@application/json^@DOCUMENT_URI^@/transmission/rpc^@DOCUMENT_ROOT^@/dev/null^@SCGI^@1^@SERVER_PROTOCOL^@HTTP/1.1^@REQUEST_SCHEME^@http^@REMOTE_ADDR^@195.114.146.218^@REMOTE_PORT^@52384^@SERVER_PORT^@8000^@SERVER_NAME^@^@HTTP_ACCEPT_ENCODING^@gzip^@HTTP_USER_AGENT^@Google-HTTP-Java-Client/1.22.0 (gzip)^@HTTP_CONTENT_TYPE^@application/json^@HTTP_CONTENT_LENGTH^@344^@HTTP_HOST^@1.1.1.1:8000^@HTTP_CONNECTION^^@Keep-Alive^@,{"method":"torrent-get","arguments":{"fields":["id","name","percentDone","totalSize","addedDate","status","rateDownload","rateUpload","uploadedEver","uploadRatio","eta","error","errorString","isFinished","sizeWhenDone","leftUntilDone","peersGettingFromUs","peersSendingToUs","webseedsSendingToUs","queuePosition","recheckProgress","doneDate"]}}
---
^@Status: 200 OK
Content-Type: text/xml
Content-Length: 356

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Call XML not a proper XML-RPC call.  Call is not valid XML.  not well-formed</string></value></member>
</struct></value>
</fault>
</methodResponse>
```

It looks like it does not read or convert linebreaks, although it just mightbe 

### Expected behaviour

XMLRPC works

### Actual behaviour

It does not

### Steps to reproduce

-

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.883GiB
 Name: rtorr
 ID: 3BMR:JPE6:C3IU:R5CO:UONH:DQBX:TD4T:FSQQ:6I25:NR7E:3T5X:BB5K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

`docker-compose version 1.29.2, build unknown`

`Linux rtorr 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Docker compose

```yaml
ervices:
  geoip-updater:
    environment:
      DOWNLOAD_PATH: /data
      EDITION_IDS: GeoLite2-City,GeoLite2-Country
      LICENSE_KEY: ''
      LOG_JSON: "false"
      LOG_LEVEL: info
      SCHEDULE: 0 0 * * 0
      TZ: Europe/Paris
    image: crazymax/geoip-updater:latest
    restart: always
    volumes:
    - /app/data/geoip:/data:rw
  rtorrent-logs:
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      rtorrent-rutorrent:
        condition: service_started
    image: bash
    restart: always
    volumes:
    - /app/data/rtorrent/log:/log:rw
  rtorrent-rutorrent:
    environment:
      AUTH_DELAY: 0s
      LOG_ACCESS: "true"
      LOG_IP_VAR: remote_addr
      MAX_FILE_UPLOADS: '50'
      MEMORY_LIMIT: 256M
      OPCACHE_MEM_SIZE: '128'
      PGID: '1000'
      PUID: '1000'
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      RT_DHT_PORT: '6881'
      RT_INC_PORT: '50000'
      RT_LOG_EXECUTE: "false"
      RT_LOG_LEVEL: debug
      RT_LOG_XMLRPC: "true"
      RUTORRENT_AUTHBASIC_STRING: ruTorrent restricted access
      RUTORRENT_PORT: '8080'
      RU_DO_DIAGNOSTIC: "true"
      RU_FORBID_USER_SETTINGS: "false"
      RU_HTTP_TIME_OUT: '30'
      RU_HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101
        Firefox/12.0
      RU_HTTP_USE_GZIP: "true"
      RU_LOCALE: UTF8
      RU_LOG_FILE: /data/rutorrent/rutorrent.log
      RU_LOG_RPC_CALLS: "false"
      RU_LOG_RPC_FAULTS: "true"
      RU_OVERWRITE_UPLOADED_TORRENTS: "false"
      RU_PHP_GZIP_LEVEL: '2'
      RU_PHP_USE_GZIP: "false"
      RU_REMOVE_CORE_PLUGINS: erasedata,httprpc
      RU_RPC_TIME_OUT: '5'
      RU_SAVE_UPLOADED_TORRENTS: "true"
      RU_SCHEDULE_RAND: '10'
      TZ: Europe/Paris
      UPLOAD_MAX_SIZE: 16M
      WAN_IP_CMD: "false"
      WEBDAV_AUTHBASIC_STRING: WebDAV restricted access
      WEBDAV_PORT: '9000'
      XMLRPC_AUTHBASIC_STRING: rTorrent XMLRPC restricted access
      XMLRPC_PORT: '8000'
    expose:
    - 6881/udp
    - '8000'
    - '8080'
    - '9000'
    - '50000'
    image: crazymax/rtorrent-rutorrent:latest
    ports:
    - protocol: udp
      published: 6881
      target: 6881
    - protocol: tcp
      published: 8080
      target: 8080
    - protocol: tcp
      published: 9000
      target: 9000
    - protocol: tcp
      published: 50000
      target: 50000
    - protocol: tcp
      published: 8000
      target: 8000
    restart: always
    ulimits:
      nofile:
        hard: 40000
        soft: 32000
      nproc: 65535
    volumes:
    - /app/data:/data:rw
    - /app/downloads:/downloads:rw
    - /app/passwd:/passwd:rw
version: '3.2'
```

### Container logs

-
