### ISSUE TITLE
Filedrop fails to load

### ISSUE THREAD

**Issue by ThisIsSet-L** [crazy-max/docker-rtorrent-rutorrent#222]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating to latest 2d1eb29c78c3, this error appears:

```
[20.03.2023 05:45:45] JS error: [http://192.168.50.189:9091/plugins/filedrop//jquery.filedrop.js : 28] Uncaught TypeError: Cannot read properties of undefined (reading 'push')
[20.03.2023 05:45:45] JS error: [http://192.168.50.189:9091/ : 2584] Uncaught TypeError: $(...).filedrop is not a function
```

Drag and drop file functionality is impacted.

### Expected behaviour

Drag and drop files should add torrent files.

### Actual behaviour

Drag and drop files causes the browser to act as if the file is being opened by the browser itself.

### Steps to reproduce

1. Pull latest image
2. Load webpage
3. Note error in Log
4. Drop torrent file
5. Note torrent not added.

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.15.1)

Server:
 Containers: 18
  Running: 14
  Paused: 0
  Stopped: 4
 Images: 34
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.7-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.52GiB
 Name: shinyakogami
 ID: XI5B:YQVV:JHJZ:HK5O:6V54:QHSQ:S7LK:I63L:CQSB:MBZT:X2IN:ERBJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`): Docker Compose version 2.15.1
* System info (type `uname -a`): Linux shinyakogami 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux

### Docker compose

```yaml
rutorrent:
    container_name: rutorrent
    environment:
      PGID: "1000"
      PUID: "1000"
    image: ghcr.io/crazy-max/rtorrent-rutorrent
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "9091"
      protocol: tcp
    - mode: ingress
      target: 8000
      published: "5000"
      protocol: tcp
    - mode: ingress
      target: 50000
      published: "50000"
      protocol: tcp
    - mode: ingress
      target: 6881
      published: "6881"
      protocol: udp
```

### Container logs

```
rutorrent  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
rutorrent  | [s6-init] ensuring user provided files have correct perms...exited 0.
rutorrent  | [fix-attrs.d] applying ownership & permissions fixes...
rutorrent  | [fix-attrs.d] done.
rutorrent  | [cont-init.d] executing container initialization scripts...
rutorrent  | [cont-init.d] 00-fix-logs.sh: executing...
rutorrent  | [cont-init.d] 00-fix-logs.sh: exited 0.
rutorrent  | [cont-init.d] 01-fix-uidgid.sh: executing...
rutorrent  | [cont-init.d] 01-fix-uidgid.sh: exited 0.
rutorrent  | [cont-init.d] 02-fix-perms.sh: executing...
rutorrent  | Fixing perms...
rutorrent  | [cont-init.d] 02-fix-perms.sh: exited 0.
rutorrent  | [cont-init.d] 03-config.sh: executing...
rutorrent  | Setting timezone to UTC...
rutorrent  | Setting PHP-FPM configuration...
rutorrent  | Setting PHP INI configuration...
rutorrent  | Setting OpCache configuration...
rutorrent  | Setting Nginx configuration...
rutorrent  | Setting Nginx XMLRPC over SCGI configuration...
rutorrent  | Setting Nginx ruTorrent configuration...
rutorrent  | Setting Nginx WebDAV configuration...
rutorrent  | Update healthcheck script...
rutorrent  | Initializing files and folders...
rutorrent  | rpc.htpasswd is empty, removing authentication...
rutorrent  | rutorrent.htpasswd is empty, removing authentication...
rutorrent  | webdav.htpasswd is empty, removing authentication...
rutorrent  | Checking rTorrent local configuration...
rutorrent  | Checking rTorrent configuration...
rutorrent  | Bootstrapping ruTorrent configuration...
rutorrent  | Setting custom config for create plugin...
rutorrent  | Checking ruTorrent custom plugins...
rutorrent  | Checking ruTorrent plugins configuration...
rutorrent  | Checking ruTorrent custom themes...
rutorrent  | Setting GeoIP2 databases for geoip2 plugin...
rutorrent  | Fixing perms...
rutorrent  | [cont-init.d] 03-config.sh: exited 0.
rutorrent  | [cont-init.d] 04-create-services.sh: executing...
rutorrent  | [cont-init.d] 04-create-services.sh: exited 0.
rutorrent  | [cont-init.d] ~-socklog: executing...
rutorrent  | [cont-init.d] ~-socklog: exited 0.
rutorrent  | [cont-init.d] done.
rutorrent  | [services.d] starting services
rutorrent  | [services.d] done.
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: using the "epoll" event method
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: nginx/1.22.1
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: OS: Linux 6.1.7-arch1-1
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: getrlimit(RLIMIT_NOFILE): 1048576:1048576
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker processes
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 844
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 846
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 847
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 848
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 854
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 864
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 886
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 910
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 960
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 996
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1035
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1063
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1095
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1134
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1178
rutorrent  | 2023/03/19 19:03:38 [notice] 812#812: start worker process 1214
rutorrent  | [19-Mar-2023 19:03:38] NOTICE: fpm is running, pid 815
rutorrent  | [19-Mar-2023 19:03:38] NOTICE: ready to handle connections
rutorrent  | 192.168.50.31 - - [19/Mar/2023:19:03:41 +0000] "GET /plugins/diskspace/action.php?_=1679251527089 HTTP/1.1" 200 45 "http://192.168.50.189:9091/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41"
rutorrent  | 192.168.50.31 - - [19/Mar/2023:19:03:52 +0000] "GET /plugins/diskspace/action.php?_=1679251527090 HTTP/1.1" 200 45 "http://192.168.50.189:9091/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41"
rutorrent  | 192.168.50.31 - - [19/Mar/2023:19:04:03 +0000] "GET /plugins/diskspace/action.php?_=1679251527091 HTTP/1.1" 200 45 "http://192.168.50.189:9091/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41"
```

### Additional info

Had not updated in a very long time (6 months?)
