### ISSUE TITLE
Rutorrent interface corrupted after adding labels

### ISSUE THREAD

**Issue by waz1500** [crazy-max/docker-rtorrent-rutorrent#233]
Using version 4.0.4-0.9.8-0.13.8-r0

Whenever I try to add a label manually to many torrents 40+ by first searching for them individually, selecting it, right clicking to add the label one by one on many torrents the interface works until I refresh or revisit the page.

```
[26.04.2023 12:00:16] Bad response from server: (200 [parsererror,getuisettings]) {"webui.fls.view":0,"webui.show_cats":1,"webui.show_dets":1,"webui.needmessage":1,"webui.reqtimeout":30000,"webui.confirm_when_deleting":1,"webui.alternate_color":0,"webui.update_interval":3000,"webui.hsplit":0.88,"webui.vsplit":0.503,"webui.effects":0,"webui.fullrows":0,"webui.no_delaying_draw":1,"webui.search":-1,"webui.speedlistdl":"128,512,1024,2048,3072,4096,5120,6144,7168,8192,9216,10240","webui.speedlistul":"128,512,1024,2048,3072,4096,5120,6144,7168,8192,9216,10240","webui.ignore_timeouts":0,"webui.retry_on_error":120,"webui.closed_panels":{"ptrackers":false,"pstate":false,"plabel":true,"flabel":true,"prss":true},"webui.open_tegs.last":["[kkot-avs4] working files
```

**Steps to Reproduce**
1. Searching for the torrent name in the search box
2. Upon search results loading the torrent, right click and add a label. 
3. Repeat the search for another torrent name and add another label. 
4. Keep doing this for maybe 30+ torrents in one session and press F5 (Refresh). 
5. GUI becomes broken and interface can't be used. 

I have checked issue https://github.com/Novik/ruTorrent/issues/974 on Noviks page and the recommended solution is to delete uisettings.json. 
I couldn't find this file at all doing a search for all directories even in a newly spun up docker with a clean config directory.
The command I was using when I was in the config directory was `sudo find . -type f -name "uisettings.json"`

I am also using the reverse proxy traefik that matches the example template provided and Authelia so I wonder if this issue may be connected to those services in which case, I can investigate further. I've attached the header file my traefik uses when I browse my rutorrent page.

```
Traefik default headers
    default-headers-rutorrent:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        STSSeconds: 31536000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
        X-Forwarded-Proto: https   
```

*Update. Issue is still occuring even after disabling the Traefik default headers.
