### ISSUE TITLE
Current release doesn't utilize RU_CACHED_PLUGIN_LOADING

### ISSUE THREAD

**Issue by coanghel** [crazy-max/docker-rtorrent-rutorrent#241]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Current release queries the plugin data rather than using cache.

### Expected behaviour

Load plugin data from cache.

### Actual behaviour

Plugin data is queried.

### Steps to reproduce

Compare network monitoring of current and previous releases.

![current](https://user-images.githubusercontent.com/9924637/236861057-155e8232-0f21-4da0-868e-b2dfedd172ff.png)
![prev](https://user-images.githubusercontent.com/9924637/236861058-cc2f7df7-491e-4b28-a9bc-76c28d67ee5d.png)

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-71-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 29.21GiB
 Name: wyse-server-01
 ID: RXTX:73SS:OX4T:ONPQ:I4Q7:MIDX:3MPP:6UZX:BUXO:F45W:YYDY:6TVG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

Linux wyse-server-01 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
N/A
```

### Container logs

[rtorrent_logs.txt](https://github.com/crazy-max/docker-rtorrent-rutorrent/files/11422345/rtorrent_logs.txt)
