### ISSUE TITLE
Plugins not getting initialized on startup, but only after first visit to the GUI (or manual init)

### ISSUE THREAD

**Issue by KoenDeMol** [crazy-max/docker-rtorrent-rutorrent#247]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I did find some other posts on other forums, but none that brought me to the solution.

After reboot of the docker container, the plugins are not initialized. Even though the execute2 line is in .rtlocal.rc (as documentend), that script is never called (I added logging). Because of that plugins (like autotools, folder watch, .. ) are not started. 

### Expected behaviour

The execute2 line (in the .rtlocal.rc file) containing the initplugins script should run on start of the rtorrent service making autotools run (and watch folders) without having to browse to the GUI.

### Actual behaviour

I have no idea why, but the execute2 line is not called. Might be an issue with (reading) the .rtlocal.rc file, or with the point and which execute2 is to be called. Anyways ... autotools is not running, files in the watch folders are not picked up.

### Steps to reproduce

- Install the container from repo
- Run
- Put a file in the watch directory
- It will not be picked up

(What I also did:
- add a line in the initplugins.php file that writes a log with timestamp to a file
- reboot
- there will be no log
- run the initplugins.php manually
- the log is there (and files are getting picked up)

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.17-qnap10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay qnet
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux kata-runtime runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309f
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60-qnap
 Operating System: QTS 5.0.1 (20230421)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.48GiB
 Name: NAS-FIT
 ID: UHS4:KBV3:QK67:X3WQ:DYN3:COMX:BFFR:AVK6:CT3K:M5DU:JJ6X:CDVF
 Docker Root Dir: /share/CACHEDEV2_DATA/vm/docker/container-station-data/lib/docker
 Debug Mode: true
  File Descriptors: 186
  Goroutines: 94
  System Time: 2023-06-05T17:26:58.942786918+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 172.29.0.0/16, Size: 22
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

Linux NAS-FIT 5.10.60-qnap #1 SMP Fri Apr 21 00:44:05 CST 2023 x86_64 GNU/Linux

### Docker compose

```yaml
N/A :: Qnap container
```

### Container logs

N/A

### Additional info

I tried numerous things, including but not limited to:
- adding the execute2 line into .rtorrent.rc file of the rtorrent user
- changing that line, not to include the user
- create start scripts in the Alpine container (these run too early).
- performing a wget to the GUI (to imitate a site visit, but I guess the reply has to be parsed en executed for it to work)

In the end, what did work for me:
- adding cron to the s6 services of the container
- configuring cron to run /usr/bin/php /var/www/rutorrent/php/initplugins.php & (WITHOUT USER!)

But I guess that is really a workarround and not a solution.
