### ISSUE TITLE
No space left on the device

### ISSUE THREAD

**Issue by rtmlp** [crazy-max/docker-rtorrent-rutorrent#276]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi. I have added rutorrent to my container stack and strangely I am noticing the following error in the log file

```
rtorrent: Error in option file: ~/.rtorrent.rc:51: Call to inotify_add_watch(...) failed: No space left on device
```

and the UI shows up like this

<img width="1277" alt="image" src="https://github.com/crazy-max/docker-rtorrent-rutorrent/assets/23462596/d01a15cb-9f70-4e0d-8c1c-a5750ff3032e">

I have used the following code to start the container (inside the compose file)
```
  rutorrent:
    container_name: rutorrent
    image: ghcr.io/crazy-max/rtorrent-rutorrent:latest
    environment:
      - PUID=1029
      - PGID=100
      - XMLRPC_PORT=7000 # XMLRPC port through nginx over SCGI socket
      - RUTORRENT_PORT=6080 # ruTorrent HTTP port
      - WEBDAV_PORT=9010 # WebDAV port on completed downloads
      - RT_INC_PORT=28277 # Port forwarding - Incoming connections (network.port_range.set)
      - RT_DHT_PORT=6881 # DHT UDP port (for DHT to work, this port must be open)/(dht.port.set)
    volumes:
      - "/path/docker/rutorrent/data:/data"
      - "/path/docker/rutorrent/passwd:/passwd"
      - "/path/data/torrents/completed:/downloads"
      - "/path/data/uploads:/uploads" # mainly to upload torrents
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
```

And in gluetun, I have the following ports forwarded
```
      # rutorrent
      - "7000:7000" # XMLRPC_PORT
      - "6080:6080" # RUTORRENT_PORT
      - "9010:9010" # WEBDAV_PORT
      - "6881:6881/udp" # RT_DHT_PORT
```

### Expected behaviour

The container should be running and should have connection to the rtorrent

### Actual behaviour

rutorrent not able to connect to rtorrent

### Steps to reproduce

Not sure

### Docker info

```text
Added the docker logs
```

### Docker Compose config

```yaml
Added the compose config in the main text
```

### Logs

```text
Added the logs in the main text
```
