### ISSUE TITLE
Not all session files are loaded.

### ISSUE THREAD

**Issue by AntAreS24** [crazy-max/docker-rtorrent-rutorrent#332]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm porting from a bare metal rtorrent to this docker image. The first time I loaded the image using docker compose, no file is loaded from the previous instance (on purpose). I then shutdown docker image, copy the session files over (~950 torrents) and restart the image. I can see all 950 torrent in rutorrent.

If I need to stop and restart the instance, only ~1/2 are now loaded (510 instead of 950). This halfing continues until it reaches 30 torrent only. The torrent loaded as not necessarily the same as the previous 1/2. It seems it's loading the session files randomly.

All session files are still present in the file system, so I know nothing has been deleted.

I tried to add the `stop_grace_period: 120s` in the compose.yml file., but same result.

I'm guessing it has to do with the loading/shutdown time, but I'm not sure which parameter to change.

### Expected behaviour

All torrents/session to be loaded every time on restart.

### Actual behaviour

Only 1/2 torrents/session loaded.

### Steps to reproduce

1. Start docker compose with no prior data.
2. Stop docker compose
3. Copy over session files (*.torrent *.torrent.rtorrent, *.torrent.libtorrent_resume)
4. Start docker compose again
5. Stop docker compose
6. Start docker compose again

### Docker info

```text
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-105-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.37GiB
 Name: homeserver
 ID: 49a8d0fc-8cb2-4e84-9828-b9078386d576
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: rtorrent-rutorrent
services:
  rtorrent-logs:
    command:
    - bash
    - -c
    - tail -f /log/*.log
    container_name: rtorrent-rutorrent-logs
    depends_on:
      rtorrent-rutorrent:
        condition: service_started
        required: true
    image: bash
    network_mode: none
    restart: always
    volumes:
    - type: bind
      source: /media/nas/rtorrent/log
      target: /log
      bind:
        create_host_path: true
  rtorrent-rutorrent:
    container_name: rtorrent-rutorrent
    environment:
      AUTH_DELAY: 0s
      LOG_ACCESS: "true"
      LOG_IP_VAR: remote_addr
      MAX_FILE_UPLOADS: "50"
      MEMORY_LIMIT: 1024M
      OPCACHE_MEM_SIZE: "128"
      PGID: "1000"
      PUID: "1000"
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      RT_DHT_PORT: "6881"
      RT_INC_PORT: "50000"
      RT_LOG_EXECUTE: "false"
      RT_LOG_LEVEL: info
      RT_LOG_XMLRPC: "false"
      RT_SESSION_SAVE_SECONDS: "2400"
      RU_DO_DIAGNOSTIC: "true"
      RU_FORBID_USER_SETTINGS: "false"
      RU_HTTP_TIME_OUT: "30"
      RU_HTTP_USE_GZIP: "true"
      RU_HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101
        Firefox/12.0
      RU_LOCALE: UTF8
      RU_LOG_FILE: /data/rutorrent/rutorrent.log
      RU_LOG_RPC_CALLS: "false"
      RU_LOG_RPC_FAULTS: "true"
      RU_OVERWRITE_UPLOADED_TORRENTS: "false"
      RU_PHP_GZIP_LEVEL: "2"
      RU_PHP_USE_GZIP: "false"
      RU_REMOVE_CORE_PLUGINS: httprpc
      RU_RPC_TIME_OUT: "5"
      RU_SAVE_UPLOADED_TORRENTS: "true"
      RU_SCHEDULE_RAND: "10"
      RUTORRENT_AUTHBASIC_STRING: ruTorrent restricted access
      RUTORRENT_PORT: "8080"
      TZ: Australia/Sydney
      UPLOAD_MAX_SIZE: 16M
      WAN_IP_CMD: "false"
      WEBDAV_AUTHBASIC_STRING: WebDAV restricted access
      WEBDAV_PORT: "9000"
      XMLRPC_AUTHBASIC_STRING: rTorrent XMLRPC restricted access
      XMLRPC_PORT: "8000"
    expose:
    - 6881/udp
    - "8000"
    - "8080"
    - "9000"
    - "50000"
    image: crazymax/rtorrent-rutorrent:latest
    networks:
      rtorrent-rutorrent: null
    ports:
    - target: 6881
      published: "6881"
      protocol: udp
    - target: 8080
      published: "8080"
      protocol: tcp
    - target: 9000
      published: "9000"
      protocol: tcp
    - target: 50000
      published: "50000"
      protocol: tcp
    restart: always
    stop_grace_period: 2m0s
    ulimits:
      nofile:
        soft: 32000
        hard: 40000
      nproc: 65535
    volumes:
    - type: bind
      source: /media/nas
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /media/nas/download
      target: /downloads
      bind:
        create_host_path: true
    - type: bind
      source: /media/nas/passwd
      target: /passwd
      bind:
        create_host_path: true
    - type: volume
      source: movies
      target: /media/Movies
      volume: {}
    - type: volume
      source: tv
      target: /media/Series
      volume: {}
networks:
  rtorrent-rutorrent:
    name: rtorrent-rutorrent
volumes:
  movies:
    name: rtorrent-rutorrent_movies
    driver_opts:
      device: //192.168.0.10/Movies
      o: vers=3.0,_netdev,file_mode=0777,dir_mode=0777,
      type: cifs
  tv:
    name: rtorrent-rutorrent_tv
    driver_opts:
      device: //192.168.0.10/Series
      o: vers=3.0,_netdev,file_mode=0777,dir_mode=0777,
      type: cifs
```

### Logs

```text
rtorrent-rutorrent-logs  | 1713932318 N rtorrent main: Starting thread.
rtorrent-rutorrent-logs  | 1713932318 N rtorrent scgi: Starting thread.
rtorrent-rutorrent-logs  | 1713932396 E 8F2E0E89A561553A0F782D32C7D792F79055D5EE->file_list: Failed to prepare file list: Could not create directory '/media/nas/download': No such file or directory
rtorrent-rutorrent-logs  | 1713932396 E Could not resume download: Could not create directory '/media/nas/download': No such file or directory
rtorrent-rutorrent-logs  | 1714193248 N rtorrent scgi: Shutting down thread.
rtorrent-rutorrent-logs  | 1714193297 N rtorrent main: Shutting down thread.
rtorrent-rutorrent-logs  | 1714193297 N rtorrent disk: Shutting down thread.
rtorrent-rutorrent-logs  | 1714193399 N rtorrent main: Starting thread.
rtorrent-rutorrent-logs  | 1714193399 N rtorrent scgi: Starting thread.
rtorrent-rutorrent       | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
rtorrent-rutorrent       | [s6-init] ensuring user provided files have correct perms...exited 0.
rtorrent-rutorrent       | [fix-attrs.d] applying ownership & permissions fixes...
rtorrent-rutorrent       | [fix-attrs.d] done.
rtorrent-rutorrent       | [cont-init.d] executing container initialization scripts...
rtorrent-rutorrent       | [cont-init.d] 00-fix-logs.sh: executing...
rtorrent-rutorrent       | [cont-init.d] 00-fix-logs.sh: exited 0.
rtorrent-rutorrent       | [cont-init.d] 01-fix-uidgid.sh: executing...
rtorrent-rutorrent       | [cont-init.d] 01-fix-uidgid.sh: exited 0.
rtorrent-rutorrent       | [cont-init.d] 02-fix-perms.sh: executing...
rtorrent-rutorrent       | Fixing perms...
rtorrent-rutorrent       | [cont-init.d] 02-fix-perms.sh: exited 0.
rtorrent-rutorrent       | [cont-init.d] 03-config.sh: executing...
rtorrent-rutorrent       | Setting timezone to Australia/Sydney...
rtorrent-rutorrent       | Setting PHP-FPM configuration...
rtorrent-rutorrent       | Setting PHP INI configuration...
rtorrent-rutorrent       | Setting OpCache configuration...
rtorrent-rutorrent       | Setting Nginx configuration...
rtorrent-rutorrent       | Setting Nginx XMLRPC over SCGI configuration...
rtorrent-rutorrent       | Setting Nginx ruTorrent configuration...
rtorrent-rutorrent       | Setting Nginx WebDAV configuration...
rtorrent-rutorrent       | Update healthcheck script...
rtorrent-rutorrent       | Initializing files and folders...
rtorrent-rutorrent       | rpc.htpasswd is empty, removing authentication...
rtorrent-rutorrent       | rutorrent.htpasswd is empty, removing authentication...
rtorrent-rutorrent       | webdav.htpasswd is empty, removing authentication...
rtorrent-rutorrent       | Checking rTorrent local configuration...
rtorrent-rutorrent       | Checking rTorrent configuration...
rtorrent-rutorrent       | Bootstrapping ruTorrent configuration...
rtorrent-rutorrent       | Removing core plugin httprpc...
rtorrent-rutorrent       | Setting custom config for create plugin...
rtorrent-rutorrent       | Checking ruTorrent custom plugins...
rtorrent-rutorrent       | Checking ruTorrent plugins configuration...
rtorrent-rutorrent       | Checking ruTorrent custom themes...
rtorrent-rutorrent       | Setting GeoIP2 databases for geoip2 plugin...
rtorrent-rutorrent       | Fixing perms...
rtorrent-rutorrent       | [cont-init.d] 03-config.sh: exited 0.
rtorrent-rutorrent       | [cont-init.d] 04-create-services.sh: executing...
rtorrent-rutorrent       | [cont-init.d] 04-create-services.sh: exited 0.
rtorrent-rutorrent       | [cont-init.d] ~-socklog: executing...
rtorrent-rutorrent       | [cont-init.d] ~-socklog: exited 0.
rtorrent-rutorrent       | [cont-init.d] done.
rtorrent-rutorrent       | [services.d] starting services
rtorrent-rutorrent       | [services.d] done.
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: using the "epoll" event method
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: nginx/1.24.0
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: OS: Linux 5.15.0-105-generic
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: getrlimit(RLIMIT_NOFILE): 32000:40000
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: start worker processes
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: start worker process 541
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: start worker process 542
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: start worker process 543
rtorrent-rutorrent       | 2024/04/27 14:49:59 [notice] 508#508: start worker process 545
rtorrent-rutorrent       | [27-Apr-2024 14:49:59] NOTICE: fpm is running, pid 511
rtorrent-rutorrent       | [27-Apr-2024 14:49:59] NOTICE: ready to handle connections
rtorrent-rutorrent       | 192.168.2.196 - - [27/Apr/2024:14:50:05 +1000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
rtorrent-rutorrent       | 192.168.2.196 - - [27/Apr/2024:14:50:06 +1000] "GET /php/getsettings.php?_=1714193405813 HTTP/1.1" 200 4866 "http://192.168.0.3:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
```
