### ISSUE TITLE
rtorrent.rc config error

### ISSUE THREAD

**Issue by bluasoar** [crazy-max/docker-rtorrent-rutorrent#340]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to setup cross-seed with rutorrent and I am getting an error when I input the following line into .rtorrent.rc 

"echo 'method.insert=d.data_path,simple,"if=(d.is_multi_file),(cat,(d.directory),/),(cat,(d.directory),/,(d.name))"' >> .rtorrent.rc"

I get an error when trying to launch rutorrent 

"rtorrent: Error in option file: ~/.rtorrent.rc:66: Invalid key."

line 66 is the above echo. I am wondering if there is anything I can change to stop this error. I didn't see any previous issues mentioning this specific issue. 

[Cross-seed Documentation](https://www.cross-seed.org/docs/basics/daemon#set-up-automatic-searches-for-finished-downloads)

### Expected behaviour

When a download finishes in ruTorrent it calls that script and searched for possible cross-seeds on available indexers.

### Actual behaviour

ruTorrent isn't able to launch due to the echo command line. I can get ruTorrent to launch by taking out this command but then cross-seed isn't usable.

### Steps to reproduce

echo 'method.insert=d.data_path,simple,"if=(d.is_multi_file),(cat,(d.directory),/),(cat,(d.directory),/,(d.name))"' >> .rtorrent.rc 

putting the above into .rtorrent.rc

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.21.0)

Server:
 Containers: 63
  Running: 49
  Paused: 0
  Stopped: 14
 Images: 128
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a6
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.64-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.28GiB
 Name: Tower
 ID: XAZY:7CWC:J5TJ:Q7H5:BGQ2:MM3Z:YBWL:IPPQ:IQEN:Q3IC:6QRI:KK3V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: n0raa
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Docker Compose config

```yaml
services:
  gluetunn:
    cap_add:
    - NET_ADMIN
    container_name: gluetunn
    environment:
      FIREWALL_OUTBOUND_SUBNETS: 192.168.20.5/32
      FIREWALL_VPN_INPUT_PORTS: 
      HTTPPROXY: "on"
      PGID: "100"
      PUID: "99"
      SERVER_CITIES: Chicago Illinois
      TZ: EST
      VPN_SERVICE_PROVIDER: airvpn
      VPN_TYPE: wireguard
      WIREGUARD_ADDRESSES: 10.190.29.188/32
      WIREGUARD_PRESHARED_KEY: REDACTED
      WIREGUARD_PRIVATE_KEY: REDACTED
    image: qmcgaw/gluetun:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      net.unraid.docker.icon: ""
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: ""
      net.unraid.docker.webui: ""
    network_mode: internal
    ports:
    - mode: ingress
      target: 8025
      published: "8025"
      protocol: tcp
    - mode: ingress
      target: 8095
      published: "8095"
      protocol: tcp
    - mode: ingress
      target: 63572
      published: "63572"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /dev/net/tun
      target: /dev/net/tun
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/cache_1tb/appdata/gluetunn
      target: /gluetun
      bind:
        create_host_path: true
  rutorrent:
    container_name: rutorrent
    depends_on:
      gluetunn:
        condition: service_started
        required: true
    environment:
      PGID: "100"
      PUID: "99"
      RT_INC_PORT: "63572"
      RUTORRENT_PORT: "8095"
      XMLRPC_PORT: "8025"
    image: crazymax/rtorrent-rutorrent
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      net.unraid.docker.icon: https://github.com/superboki/ressources/blob/main/rutorrent-crazymax/rutorrent-crazymax.png?raw=true
      net.unraid.docker.managed: composeman
      net.unraid.docker.shell: ""
      net.unraid.docker.webui: http://[IP]:[PORT:8095]/
    network_mode: service:gluetunn
    volumes:
    - type: bind
      source: /mnt/cache_1tb/appdata/rutorrent
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/user/data/torrents
      target: /downloads
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/cache_1tb/appdata/rutorrent/passwd
      target: /passwd
      bind:
        create_host_path: true
```

### Logs

```text
rtorrent: Error in option file: ~/.rtorrent.rc:66: Invalid key.

Spammed repeatedly.
```
