### ISSUE TITLE
Docker image broke for me with yesterdays push.

### ISSUE THREAD

**Issue by VictorioBerra** [crazy-max/docker-rtorrent-rutorrent#342]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

watchtower updated my container, and everything broke.

> rtorrent: Failed to parse command line option: Error in option file: /etc/rtorrent/.rtlocal.rc:50: Not a value.

### Expected behaviour

container image should be able to do a minor update without breaking.

### Actual behaviour

> rtorrent: Failed to parse command line option: Error in option file: /etc/rtorrent/.rtlocal.rc:50: Not a value.

### Steps to reproduce

1. Unkown yet.

### Docker info

```text
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.28+rpt-rpi-2712
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.864GiB
 Name: pinas
 ID: 39cc2a12-59bc-4e12-b2b5-de8c82b0edd0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Docker Compose config

```yaml
rtorrent:
        restart: always
        container_name: rtorrent
        image: 'crazymax/rtorrent-rutorrent:latest'
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
        ports:
            - '6881:6881/udp'
            - '8000:8000'
            - '8080:8080'
            - '9000:9000'
            - '50000:50000'
        volumes:
            - '/mnt/usb/data:/data'
            - '/mnt/usb/downloads:/downloads'
            - '/mnt/usb/passwd:/passwd'
```

### Logs

```text
> rtorrent: Failed to parse command line option: Error in option file: /etc/rtorrent/.rtlocal.rc:50: Not a value.
```
