### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by neo-neo1** [crazy-max/docker-rtorrent-rutorrent#39]
Could someone share their docker-compose file for this docker? All of the linuxserver dockers include a respective docker-compose which I find very useful. 

Note: v2 of docker-compose is preferred as [v3 is not compatible](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/examples/compose/docker-compose.yml) with portianer.

**Comment by gauth-fr** [comment]
here is mine, with the traefik v2 + letsencrypt (v2.2.1 in my case) in bonus:
```
version: "2"

services:
  rtorrentfb:
    image:  crazymax/rtorrent-rutorrent:3.9-0.9.8-0.13.8
    container_name: rtorrentfb
    ports:
      - "6881:6881/udp"
      - "50000:50000"
    environment:
      - UID=1000
      - GID=1000
      - RT_LOG_LEVEL=debug
      - RT_LOG_EXECUTE=true
      - RT_LOG_XMLRPC=false
      - TZ=Europe/Paris
    volumes:
      - "/home/user/docker-config/rtorrent-rutorrent:/data"
      - "/home/user/files:/downloads"
      - "/home/user/docker-config/passwd:/passwd"
    labels:
      - traefik.enable=true
      
      ####HTTP ROUTER
      - "traefik.http.routers.rutorrent.entrypoints=web"
      - "traefik.http.routers.rutorrent.rule=Host(`rutorrent.mydomain.com`)"
      - "traefik.http.routers.rutorrent.middlewares=https-redirect@file"
      - "traefik.http.routers.rutorrent.service=rutorrent"
      #####HTTPS ROUTER
      - "traefik.http.routers.rutorrent-secure.entrypoints=websecure"
      - "traefik.http.routers.rutorrent-secure.rule=Host(`rutorrent.mydomain.com`)"
      - "traefik.http.routers.rutorrent-secure.middlewares=auth-seedbox@file"
      - "traefik.http.routers.rutorrent-secure.tls=true"
      - "traefik.http.routers.rutorrent-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.rutorrent-secure.service=rutorrent"
      - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"

      ###HTTP ROUTER
      - "traefik.http.routers.webdav.entrypoints=web"
      - "traefik.http.routers.webdav.rule=Host(`webdav.mydomain.com`)"
      - "traefik.http.routers.webdav.middlewares=https-redirect@file"
      - "traefik.http.routers.webdav.service=webdav"
      #####HTTPS ROUTER
      - "traefik.http.routers.webdav-secure.entrypoints=websecure"
      - "traefik.http.routers.webdav-secure.rule=Host(`webdav.mydomain.com`)"
      - "traefik.http.routers.webdav-secure.middlewares=auth-seedbox@file"
      - "traefik.http.routers.webdav-secure.tls=true"
      - "traefik.http.routers.webdav-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.webdav-secure.service=webdav"
      - "traefik.http.services.webdav.loadbalancer.server.port=9000"
      
      ###HTTP ROUTER
      - "traefik.http.routers.scgi.entrypoints=web"
      - "traefik.http.routers.scgi.rule=Host(`scgi.mydomain.com`)"
      - "traefik.http.routers.scgi.middlewares=https-redirect@file"
      - "traefik.http.routers.scgi.service=scgi"
      #####HTTPS ROUTER
      - "traefik.http.routers.scgi-secure.entrypoints=websecure"
      - "traefik.http.routers.scgi-secure.rule=Host(`scgi.mydomain.com`)"
      - "traefik.http.routers.scgi-secure.middlewares=auth-seedbox@file"
      - "traefik.http.routers.scgi-secure.tls=true"
      - "traefik.http.routers.scgi-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.scgi-secure.service=scgi"
      - "traefik.http.services.scgi.loadbalancer.server.port=8000"
      
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped
```

In case here is my traefik config:
```
traefik:
    image: "traefik:latest"
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      #- "8082:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/docker-config/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /home/user/docker-config/traefik/traefik.config.toml:/etc/traefik/traefik.config.toml:ro
      - /home/user/docker-config/traefik/acme.json:/acme.json
      - /var/log/traefik:/var/log
    labels:
      - "traefik.enable=true"
      #- "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      ####HTTP ROUTER
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      #####HTTPS ROUTER
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.mydomain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=auth-admin@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
      - proxy
    restart: unless-stopped
  
```

And to be complete, the traefik toml files
**traefik.toml**
```
[global]
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

[accessLog]
  filePath = "/var/log/access.log"
  [accessLog.filters]    
    statusCodes = ["400-499"]  

  [accessLog.fields]
    defaultMode = "keep"
	[accessLog.fields.names]
	  "StartUTC" = "drop"
    [accessLog.fields.headers]
      defaultMode = "keep"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
    swarmMode = false
  [providers.file]
    filename = "/etc/traefik/traefik.config.toml"
    watch = true

[api]
  dashboard = true
  debug = false
#  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "mail@mail.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

```

**traefik.config.toml**
```
	# Declaring the user list
[http.middlewares]
  [http.middlewares.auth-seedbox.basicAuth]
    users = [
      "user:encoded_password", 
    ]
    realm = "Seedbooox"
  
  [http.middlewares.auth-admin.basicAuth]
    users = [
      "user:encoded_password", 
    ]
    realm = "Seedbooox"
  
  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true
```

You should be good to go ;)
