### ISSUE TITLE
rtorrent failures since 4.3.5-5.1

### ISSUE THREAD

**Issue by antoine-morvan** [crazy-max/docker-rtorrent-rutorrent#396]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since a recent update of the image, I get some errors from rutorrent. I cleared my previous sessions and started with a clean, minimal setup (see docker compose config below). I then tested with a torrent from ubuntu (server image from https://ubuntu.com/download/alternative-downloads ).

The error I get within ruTorrent is like this :

![image](https://github.com/user-attachments/assets/2546d594-70b5-4e4c-b590-210077e28fd1)

That seems to indicate the XMLRPC link is down and rtorrent is not responding. When checking the logs from the container, I can indeed observe some error messages (keeps printing the message, just post 2 iterations here) :

```
rutorrent-1  | Caught Illegal instruction, dumping stack:
rutorrent-1  | Stack dump not enabled.
rutorrent-1  | Caught Illegal instruction, dumping stack:
rutorrent-1  | Stack dump not enabled.
```

I can reproduce with versions 4.3.5-5.1 and 4.3.6-6.0, and cannot reproduce with version 4.3.5-4.0 (did not test prior versions).

### Expected behaviour

Should not produce errors, as it was working fine with previous versions.

### Actual behaviour

Produces errors.

### Steps to reproduce

1. Startup a fresh rtorrent+rutorrent instance using a docker compose
2. add a torrent
3. observe the error

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-25-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.903GiB
 Name: test
 ID: ddd87cfc-18f9-4c6e-8ce1-2861def5c331
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```


### Docker Compose config

```yaml
name: docker
services:
  rutorrent:
    environment:
      PGID: "1000"
      PUID: "1000"
      RT_INC_PORT: "49161"
      TZ: Europe/Paris
    image: crazymax/rtorrent-rutorrent:4.3.5-5.1
    networks:
      default: null
    ports:
      - mode: ingress
        target: 49161
        published: "49161"
        protocol: tcp
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    restart: always
    ulimits:
      nofile:
        soft: 32000
        hard: 40000
      nproc: 65535
networks:
  default:
    name: docker_default
```
```


### Logs

```text
N/A
```

### Additional info

I could not reproduce on my desktop machine : this only happens on my server hosted at OVH. I even tried with a debian VM with similar version, kernel, docker version, etc., but still could not reproduce.
