### ISSUE TITLE
Health check fails after upgrading to release 5.2.5-0.15.3-r0

### ISSUE THREAD

**Issue by newadventure079** [crazy-max/docker-rtorrent-rutorrent#443]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

After upgrading to `5.2.5-0.15.3-r0`, `/usr/local/bin/healthcheck` is failing.  The exact same setup worked before on the previous release.

My `XMLRPC_PORT` is defined as `8000` so I used `8001` below

```
rutorrent-Default:/# /usr/local/bin/healthcheck
curl: (22) The requested URL returned error: 502
rutorrent-Default:/# curl --fail -d "<?xml version='1.0'?><methodCall><methodName>system.api_version</methodName></methodCall>" http://127.0.0.1:8001
curl: (22) The requested URL returned error: 502
```

I got the commands from https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/fd8d26dc2e8f75c180ebfa438390b4da383b25a4/rootfs/etc/cont-init.d/03-config.sh#L126  The other 2 commands in `/usr/local/bin/healthcheck` dont fail.

### Expected behaviour

`/usr/local/bin/healthcheck` shouldn't fail, just like it didn't in previous releases

### Actual behaviour

```
rutorrent-Default:/# /usr/local/bin/healthcheck
curl: (22) The requested URL returned error: 502
```

### Steps to reproduce

1.  Start container
2. Wait about 30s
3. View the health of the container or run `/usr/local/bin/healthcheck` and observe `502` error

### Docker info

```text
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 24.0.2
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 067f5021280b8de2059026fb5c43c4adb0f3f244
 runc version: 0320c58
 init version: ed96d00
 Security Options:
  apparmor
 Kernel Version: 4.4.302+
 Operating System: Synology NAS

 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.77GiB
 Name: DiskStation
 ID: f71b7beb-643a-4526-9995-9ce1314e77b3
 Docker Root Dir: /volume2/@docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Docker Compose config

```yaml
version: "3.6"
services:
  rutorrent-Default:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "rutorrent-Default"
    entrypoint:
      - "/init"
    environment:
      - "RT_LOG_LEVEL=info"
      - "MAX_FILE_UPLOADS=3000"
      - "OPCACHE_MEM_SIZE=64000"
      - "XMLRPC_PORT=8000"
      - "PYTHONPATH=:/var/www/rutorrent"
      - "TZ=America/Boise"
      - "RT_INC_PORT=50002"
      - "UPLOAD_MAX_SIZE=1000M"
      - "XMLRPC_SIZE_LIMIT=16M"
      - "RU_REMOVE_CORE_PLUGINS=_cloudflare,_noty,_noty2,chunks,diskspace,cpuload,cookies,extratio,extsearch,feeds,filedrop,ipad,loginmgr,mediainfo,ratio,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,spectrogram,xmpp"
      - "RT_RECEIVE_BUFFER_SIZE=16M"
      - "PUID=1026"
      - "RT_SEND_BUFFER_SIZE=16M"
      - "S6_KILL_GRACETIME=10000"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "RT_SESSION_SAVE_SECONDS=1200"
      - "RT_TRACKER_DELAY_SCRAPE=true"
      - "MEMORY_LIMIT=64000M"
      - "LOG_ACCESS=false"
      - "RUTORRENT_PORT=9081"
      - "PGID=100"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "rutorrent-Default"
    image: "crazymax/rtorrent-rutorrent:latest"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "c07780d7c4f15f2034889040635776e17867534f94ae643b1397daf68b28cd4a"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:2c57f2a17bce19ca7fc48375501e9330746922dcdb594c7077c03558e13d6222"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "docker_compose_backups"
      com.docker.compose.service: "rutorrent-Default"
      com.docker.compose.version: "2.20.1"
      org.opencontainers.image.created: "2023-04-27T20:34:14.550Z"
      org.opencontainers.image.description: "rTorrent and ruTorrent"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "6c92fb1d17a7e3556590497b7e7cd8d9eb0fc2bd"
      org.opencontainers.image.source: "https://github.com/crazy-max/docker-rtorrent-rutorrent"
      org.opencontainers.image.title: "rTorrent and ruTorrent"
      org.opencontainers.image.url: "https://github.com/crazy-max/docker-rtorrent-rutorrent"
      org.opencontainers.image.vendor: "CrazyMax"
      org.opencontainers.image.version: "4.1.3-0.9.8-0.13.8"
    logging:
      driver: "db"
      options: {}
    networks:
      - "rutorrent"
    ports:
      - "50002:50002/tcp"
      - "6881:6881/udp"
      - "8000:8000/tcp"
      - "9000:9000/tcp"
      - "9081:9081/tcp"
    restart: "always"
    stdin_open: true
    tty: true
    volumes:
      - "/volume1/NAS/LTS:/LTS"
      - "/volume1/NAS/LTS:/volume1/NAS/LTS"
      - "/volume1/NAS/Plex:/Plex"
      - "/volume1/NAS/Torrents/Radarr:/Radarr"
      - "/volume1/NAS/Torrents/Sonarr:/Sonarr"
      - "/volume1/NAS/Torrents:/Torrents"
      - "/volume1/NAS/Torrents:/downloads"
      - "/volume1/NAS/Torrents:/volume1/NAS/Torrents"
      - "/volume1/NAS:/volume1/NAS"
      - "/volume2/docker/rutorrent-Default:/data"
      - "20c75abb4bfae1024fda390d39930e88894473d08df6bad5bca4478915b99fbe:/passwd"
    working_dir: "/"
networks:
  rutorrent:
    external: true
    name: "rutorrent"
volumes:
  20c75abb4bfae1024fda390d39930e88894473d08df6bad5bca4478915b99fbe:
    external: true
```

### Logs

```text
Health:{
FailingStreak:37,
Log:[
{
End:"2025-05-17T15:53:23.305974047-06:00",
ExitCode:22,
Output:" % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 89 0 0 100 89 0 114k --:--:-- --:--:-- --:--:-- 89000 curl: (22) The requested URL returned error: 502 ",
Start:"2025-05-17T15:53:23.257071911-06:00"
},
{
End:"2025-05-17T15:53:53.370662979-06:00",
ExitCode:22,
Output:" % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 89 0 0 100 89 0 123k --:--:-- --:--:-- --:--:-- 89000 curl: (22) The requested URL returned error: 502 ",
Start:"2025-05-17T15:53:53.327113617-06:00"
},
{
End:"2025-05-17T15:54:23.441276239-06:00",
ExitCode:22,
Output:" % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 89 0 0 100 89 0 125k --:--:-- --:--:-- --:--:-- 89000 curl: (22) The requested URL returned error: 502 ",
Start:"2025-05-17T15:54:23.391397177-06:00"
},
{
End:"2025-05-17T15:54:53.505858045-06:00",
ExitCode:22,
Output:" % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 89 0 0 100 89 0 123k --:--:-- --:--:-- --:--:-- 89000 curl: (22) The requested URL returned error: 502 ",
Start:"2025-05-17T15:54:53.462987806-06:00"
},
{
End:"2025-05-17T15:55:23.565818157-06:00",
ExitCode:22,
Output:" % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 89 0 0 100 89 0 127k --:--:-- --:--:-- --:--:-- 89000 curl: (22) The requested URL returned error: 502 ",
Start:"2025-05-17T15:55:23.52648011-06:00"
}
],
Status:"unhealthy"
},
```
