### ISSUE TITLE
Container crashing with segfault after updating

### ISSUE THREAD

**Issue by Erasure5959** [crazy-max/docker-rtorrent-rutorrent#459]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

After updating the rtorrent-rutorrent container, I am experiencing crashes due to segmentation faults. I have tested the below versions:

- docker pull crazymax/rtorrent-rutorrent:5.2.8-0.15.4
- docker pull crazymax/rtorrent-rutorrent:5.2.9-0.15.4

Both of these produce the same output; the last known good version on my device is 5.2.8-0.15.3. This is on a Raspberry Pi 4.

I am running latest on another platform without any issues.

### Expected behaviour

Container runs normally and does not crash.

### Actual behaviour

Crashes due to segmentation fault.

### Steps to reproduce

1. Pull latest container image.
2. Docker compose up -d
3. Observe crashes in logs.

### Docker info

```text
Client: Docker Engine - Community
 Version:    28.2.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.24.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.36.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 28.2.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
  no-new-privileges
 Kernel Version: 5.15.92-1-osmc
 Operating System: Open Source Media Center
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.704GiB
 ID: aee5e699-3929-4e57-a770-d75fdb46fb6c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No memory limit support
WARNING: No swap limit support
```

### Docker Compose config

```yaml
name: rutorrent
services:
  geoip-updater:
    container_name: rtorrent_geoip
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "52428800"
    environment:
      DOWNLOAD_PATH: /data
      EDITION_IDS: GeoLite2-City,GeoLite2-Country,GeoLite2-ASN
      LICENSE_KEY: [REDACTED]
      LOG_JSON: "false"
      LOG_LEVEL: info
      SCHEDULE: 0 0 * * 0
      TZ: Europe/London
    image: crazymax/geoip-updater:latest
    networks:
      default: null
    restart: always
    volumes:
      - type: bind
        source: /opt/docker/rutorrent/data/geoip
        target: /data
        bind:
          create_host_path: true
  rtorrent-logs:
    command:
      - bash
      - -c
      - tail -f /log/*.log
    container_name: rtorrent_logs
    depends_on:
      rtorrent-rutorrent:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "52428800"
    image: bash
    networks:
      default: null
    restart: always
    volumes:
      - type: bind
        source: /opt/docker/rutorrent/data/rtorrent/log
        target: /log
        bind:
          create_host_path: true
  rtorrent-rutorrent:
    container_name: rtorrent
    environment:
      LOG_IP_VAR: remote_addr
      MAX_FILE_UPLOADS: "50"
      MEMORY_LIMIT: 256M
      OPCACHE_MEM_SIZE: "128"
      PGID: "1000"
      PUID: "1000"
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      RT_DHT_PORT: "6881"
      RT_INC_PORT: "9387"
      RT_LOG_EXECUTE: "false"
      RT_LOG_LEVEL: info
      RT_LOG_XMLRPC: "false"
      RU_DO_DIAGNOSTIC: "true"
      RU_FORBID_USER_SETTINGS: "false"
      RU_HTTP_TIME_OUT: "30"
      RU_HTTP_USE_GZIP: "true"
      RU_HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
      RU_LOCALE: UTF8
      RU_LOG_FILE: /data/rutorrent/rutorrent.log
      RU_LOG_RPC_CALLS: "false"
      RU_LOG_RPC_FAULTS: "true"
      RU_OVERWRITE_UPLOADED_TORRENTS: "false"
      RU_PHP_GZIP_LEVEL: "2"
      RU_PHP_USE_GZIP: "false"
      RU_RPC_TIME_OUT: "5"
      RU_SAVE_UPLOADED_TORRENTS: "true"
      RU_SCHEDULE_RAND: "10"
      RUTORRENT_AUTHBASIC_STRING: ruTorrent restricted access
      RUTORRENT_PORT: "8080"
      TZ: Europe/London
      UPLOAD_MAX_SIZE: 16M
      WEBDAV_AUTHBASIC_STRING: WebDAV restricted access
      WEBDAV_PORT: "9000"
      XMLRPC_AUTHBASIC_STRING: rTorrent XMLRPC restricted access
      XMLRPC_PORT: "8000"
    expose:
      - "8000"
      - "8080"
      - "9000"
      - "9387"
    image: crazymax/rtorrent-rutorrent:5.2.8-0.15.3
    networks:
      default: null
      dmz:
        ipv4_address: 203.0.113.2
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 9000
        published: "9000"
        protocol: tcp
      - mode: ingress
        target: 9387
        published: "9387"
        protocol: tcp
    restart: always
    ulimits:
      nofile:
        soft: 32000
        hard: 40000
      nproc: 65535
    volumes:
      - type: bind
        source: /opt/docker/rutorrent/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /media
        target: /downloads
        bind:
          create_host_path: true
      - type: bind
        source: /opt/docker/rutorrent/passwd
        target: /passwd
        bind:
          create_host_path: true
networks:
  default:
    name: rutorrent_default
  dmz:
    name: dmz
    external: true
```

### Logs

```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing... 
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing... 
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing... 
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing... 
Setting PHP-FPM configuration...
Setting PHP INI configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Setting Nginx XMLRPC over SCGI configuration...
Setting Nginx ruTorrent configuration...
Setting Nginx WebDAV configuration...
Update healthcheck script...
Initializing files and folders...
rpc.htpasswd is empty, removing authentication...
rutorrent.htpasswd is empty, removing authentication...
webdav.htpasswd is empty, removing authentication...
Checking rTorrent local configuration...
Checking rTorrent configuration...
Bootstrapping ruTorrent configuration...
Setting custom config for create plugin...
Checking ruTorrent custom plugins...
Checking ruTorrent plugins configuration...
Checking ruTorrent custom themes...
Setting GeoIP2 databases for geoip2 plugin...
Fixing perms...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-create-services.sh: executing... 
[cont-init.d] 04-create-services.sh: exited 0.
[cont-init.d] ~-socklog: executing... 
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
2025/06/19 11:34:03 [notice] 508#508: using the "epoll" event method
2025/06/19 11:34:03 [notice] 508#508: nginx/1.26.3
2025/06/19 11:34:03 [notice] 508#508: OS: Linux 5.15.92-1-osmc
2025/06/19 11:34:03 [notice] 508#508: getrlimit(RLIMIT_NOFILE): 32000:40000
2025/06/19 11:34:03 [notice] 508#508: start worker processes
2025/06/19 11:34:03 [notice] 508#508: start worker process 523
2025/06/19 11:34:03 [notice] 508#508: start worker process 524
2025/06/19 11:34:03 [notice] 508#508: start worker process 525
2025/06/19 11:34:03 [notice] 508#508: start worker process 527
[services.d] done.
[19-Jun-2025 11:34:03] NOTICE: fpm is running, pid 507
[19-Jun-2025 11:34:03] NOTICE: ready to handle connections
Caught Segmentation fault, dumping stack:
Stack dump not enabled.
Caught Segmentation fault, dumping stack:
Stack dump not enabled.
```
