### ISSUE TITLE
Watch folder is not working as expected

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#56]
Hi @crazy-max 

I have a folder mapping for the watch folder:
`- /volume1/docker/rutorrent-main/watched:/downloads/watched`

AutoWatch/AutoLabel are configured like:
![image](https://user-images.githubusercontent.com/35723598/110933139-a978d480-832c-11eb-8763-08c0d78466d3.png)

Inside the container the permission looks good
![image](https://user-images.githubusercontent.com/35723598/110932725-22c3f780-832c-11eb-8350-34dcc71af7cb.png)

The folder tv contains 93 items but they are not added to my download location /tv folder...

Do you have any hints? Is there a scan frequency? Can we configure it?

Thanks

**Comment by crazy-max** [comment]
@the-lazy-fox Watch folder is [already handled by rtorrent](https://github.com/crazy-max/docker-rtorrent-rutorrent#boostrap-config-rtlocalrc) through `/data/rtorrent/watch/` folder. No need to use the one from ruTorrent.

> The folder tv contains 93 items but they are not added to my download location /tv folder...

Also you cannot use sub folders in the watch directory. You have to place to place the torrents directly inside.

**Comment by the-lazy-fox** [comment]
Hello @crazy-max,
Yes the rtorrent one is working but doesn't manage the autolabelling and subfolders assignment like rutorrent does. Plus it doesn't remove the .torrent file when grabbing it.
This is why, with my current image (linuxserver), I always used the rutorrent one which manage all of them (labeling, folder assignment, removal on grab)
This is why I'm opening this issue has I don't get why it's not working currently.

**Comment by crazy-max** [comment]
@the-lazy-fox Just tested and works fine for me.

Create `watched` folder with some subfolders:

```shell
mkdir -p ./watched/test1 ./watched/test2
chown -R 1000:1000 ./watched
```

Create `./data/rutorrent/plugins-conf/autotools.php` configuration to adjust some settings and enable debug:

```php
<?php

        // set interval for schedule command in seconds
        $autowatch_interval = 15;

        // set "true" to enable debug output
        $autodebug_enabled = true;
```

Update compose configuration and bind mount `watched` folder:

```yaml
version: "3.2"

services:
  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    ports:
      - target: 6881
        published: 6881
        protocol: udp
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    env_file:
      - "./rtorrent-rutorrent.env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
      - "./passwd:/passwd"
      - "./watched:/watched"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
```

Compose up and enable autowatch:

![image](https://user-images.githubusercontent.com/1951866/111696128-37285880-8834-11eb-8c90-022a538e7c21.png)

Wait 15 seconds and Torrents are added as expected:

![image](https://user-images.githubusercontent.com/1951866/111696351-82426b80-8834-11eb-83fa-6b1418209794.png)

Check rutorrent logs in `./data/rutorrent/rutorrent.log`, everything looks fine:

```text
[18.03.21 21:44:44]
[18.03.21 21:44:44] AutoWatch: --- begin ---
[18.03.21 21:44:44] AutoWatch: enabled          : 1
[18.03.21 21:44:44] AutoWatch: autostart        : 0
[18.03.21 21:44:44] AutoWatch: path_to_watch    : /watched/
[18.03.21 21:44:44] AutoWatch: get_directory    : /downloads/temp/
[18.03.21 21:44:44] AutoWatch: torrent file     : /watched/test2/testa.torrent
[18.03.21 21:44:44] AutoWatch: save data to     : /downloads/temp/test2/
[18.03.21 21:44:44] AutoWatch: torrent added    : 1A226D376383920991351EFEF2DF76FD2FF9F493
[18.03.21 21:44:44] AutoWatch: torrent file     : /watched/test1/test0.torrent
[18.03.21 21:44:44] AutoWatch: save data to     : /downloads/temp/test1/
[18.03.21 21:44:44] AutoWatch: torrent added    : 608DB27A37CD74C8A2B2340CAC6314AE0BCABDCE
[18.03.21 21:44:44] AutoWatch: --- end ---
[18.03.21 21:44:44]
[18.03.21 21:44:44] AutoLabel: --- begin ---
[18.03.21 21:44:44] AutoLabel: enabled         : 1
[18.03.21 21:44:44] AutoLabel: template        : "{DIR}"
[18.03.21 21:44:44] AutoLabel: get_directory   : /downloads/temp/
[18.03.21 21:44:44] AutoLabel: d.get_directory : /downloads/temp/test2/testa
[18.03.21 21:44:44] AutoLabel: d.get_custom3   :
[18.03.21 21:44:44] AutoLabel: d.is_multy_file : 1
[18.03.21 21:44:44] AutoLabel: label           : "test2"
[18.03.21 21:44:44] rtExec: d.set_custom1
[18.03.21 21:44:44] AutoLabel: --- end ---
[18.03.21 21:44:44]
[18.03.21 21:44:44] AutoLabel: --- begin ---
[18.03.21 21:44:44] AutoLabel: enabled         : 1
[18.03.21 21:44:44] AutoLabel: template        : "{DIR}"
[18.03.21 21:44:44] AutoLabel: get_directory   : /downloads/temp/
[18.03.21 21:44:44] AutoLabel: d.get_directory : /downloads/temp/test1
[18.03.21 21:44:44] AutoLabel: d.get_custom3   :
[18.03.21 21:44:44] AutoLabel: d.is_multy_file :
[18.03.21 21:44:44] AutoLabel: label           : "test1"
[18.03.21 21:44:44] rtExec: d.set_custom1
[18.03.21 21:44:44] AutoLabel: --- end ---
[18.03.21 21:44:59]
[18.03.21 21:44:59] AutoWatch: --- begin ---
[18.03.21 21:44:59] AutoWatch: enabled          : 1
[18.03.21 21:44:59] AutoWatch: autostart        : 0
[18.03.21 21:44:59] AutoWatch: path_to_watch    : /watched/
[18.03.21 21:44:59] AutoWatch: get_directory    : /downloads/temp/
[18.03.21 21:44:59] AutoWatch: --- end ---
```
