### ISSUE TITLE
[Request] support jesec/flood UI in rtorrent

### ISSUE THREAD

**Issue by lilws** [crazy-max/docker-rtorrent-rutorrent#64]
I moved to this image and I want to setup flood to use with mobile device. But it is not fully support flood and cause a lot of bugs. flood is mean to work with rtorrent fully. Can you take a look into this issue? Here is my docker-compose. Flood connect to rtorrent use the scgi.socket. I'm not sure if I missing something else here because with this setup, it works with linuxserver image but this image is obsolete and abandoned.

```
rt:
  image: crazymax/rtorrent-rutorrent:latest
  container_name: rt
  volumes:
     - /volume1/docker/rt/data:/data
     - /volume1/docker/rt/passwd:/passwd
     - /volume1/docker/rt/rsock:/var/run/rtorrent
     - /volume3/tor:/downloads
     - /volume2/tor2:/downloads2
  env_file:
     - /volume1/docker/rt/rtorrent-rutorrent.env
  ports:
     - 30000:6881/udp
     - 5580:8080
     - 9000:9000
     - 8000:8000
  restart: always

floodru:
  image: jesec/flood:latest
  container_name: floodru
  user: PUID:PGID
  restart: always
  command: --port 3000 --rundir /config/floodjc
  volumes:
     - /volume1/docker/rt/data/:/config
     - /volume1/docker/rt/rsock:/media
     - /volume2/tor2:/downloads2
     - /volume3/tor:/downloads
  ports:
     - 3001:3000
```
