### ISSUE TITLE
Allow to change the "$topDirectory" variable in rutorrent

### ISSUE THREAD

**Issue by RaymondSchnyder** [crazy-max/docker-rtorrent-rutorrent#7]
Hey,

Could you add a variable to change the "$topdirectory" variable in rutorrent?
I want to save torrents to a folder which is on /archive.
But the default value for "$topDirectory" is "/data", so i cannot save anything under "/archive"

**Comment by crazy-max** [comment]
If we do so, it will break a lot of things. Why do you want to change that anyway?

**Comment by RaymondSchnyder** [comment]
> I want to save torrents to a folder which is on /archive.

Just make it default "/data" and adjustable if someone wants another directory.

**Comment by crazy-max** [comment]
The proper way to do this is to use custom [bind mounts](https://docs.docker.com/storage/bind-mounts/) on your side. Changing this path in the image would break Docker philosophy around volume.

**Comment by RaymondSchnyder** [comment]
> 
> 
> The proper way to do this is to use custom [bind mounts](https://docs.docker.com/storage/bind-mounts/) on your side. Changing this path in the image would break Docker philosophy around volume.

The hostpath is /mnt/data/Torrent
The volume path in the container is /archive.
I cannot change this path, as some torrents already depend on that path.
If i change  /archive to something another, rtorrent wont find any data.

I could, if its not possible in any other way, create a second mount in /data like /data/archive, so that /mnt/data/Torrent is mounted on /archive and /data/archive
So i can atleast access it within rutorrent.

**Comment by crazy-max** [comment]
> The hostpath is /mnt/data/Torrent

Ok so you bind `/mnt/data/Torrent:/data` ?

> The volume path in the container is /archive.
> I cannot change this path, as some torrents already depend on that path.
> If i change /archive to something another, rtorrent wont find any data.

Hum, I think you have customized something more than expected with this image :upside_down_face:
Can you post your docker-compose and rtorrent config ?

**Comment by RaymondSchnyder** [comment]
Description of use case:

I have a FUSE Mount on /mnt/data.
That FUSE Mount contains a Folder named TorrentData, which contains Torrents.
The torrents in that folder have the path "/archive" stored. (Other Docker Image)
The existing ones arent that of a problem, i cant switch the path IIRC, but was bothers me is that i cannot save torrents to /archive anymore.

Of course, when i download a torrent, i save it first local, so in /data.
But after i downloaded it, i would like to move it to /archive, so it doesnt uses storage on /data and i can continue seeding it.

docker-compose.yml
```
version: "3.2"

services:
  rtorrent-rutorrent:
          #    image: docker_build:latest #selfbuild image
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent-rutorrent
    ports:
      - target: 80
        published: 8088
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    env_file:
      - rtorrent-rutorrent.env
    volumes:
      - "/mnt/Torrent/rtorrent:/data"
      - "./passwd:/passwd"
      - "/mnt/Torrent:/downloads"
      - "/mnt/data:/unionfs:rw"
      - "/mnt/data/TorrentData:/archive"
        #      - type: bind
        #        source: /mnt/data/TorrentData
        #        target: /archive
        #        bind:
        #          propagation: rslave
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
```

.rtorrent.rc
```
# Maximum and minimum number of peers to connect to per torrent
throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100

network.http.ssl_verify_peer.set=0

# Same as above but for seeding completed torrents (-1 = same as downloading)
throttle.min_peers.seed.set = 0
throttle.max_peers.seed.set = 500


# Maximum number of simultanious uploads per torrent
throttle.max_uploads.set = 50

# Global upload and download rate in KiB. "0" for unlimited
throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb = 0

# XMLRPC size limit
network.xmlrpc.size_limit.set = 4M

# Enable DHT support for trackerless torrents or when all trackers are down
# May be set to "disable" (completely disable DHT), "off" (do not start DHT),
# "auto" (start and stop DHT as needed), or "on" (start DHT immediately)
dht.mode.set = disable

# Enable peer exchange (for torrents not marked private)
protocol.pex.set = no

# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported
pieces.hash.on_completion.set = yes

# Set whether the client should try to connect to UDP trackers
#trackers.use_udp.set = yes

# Set the max amount of memory address space used to mapping file chunks. This refers to memory mapping, not
# physical memory allocation. Default: 1GB (max_memory_usage)
# This may also be set using ulimit -m where 3/4 will be allocated to file chunks
#pieces.memory.max.set = 1GB

# Alternative calls to bind and ip that should handle dynamic ip's
#schedule2 = ip_tick,0,1800,ip=rakshasa
#schedule2 = bind_tick,0,1800,bind=rakshasa

# Encryption options, set to none (default) or any combination of the following:
# allow_incoming, try_outgoing, require, require_RC4, enable_retry, prefer_plaintext
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Set the umask for this process, which is applied to all files created by the program
system.umask.set = 0022

# Add a preferred filename encoding to the list
encoding.add = UTF-8

# Watch a directory for new torrents, and stop those that have been deleted
schedule2 = watch_directory, 1, 1, (cat,"load.start=",(cfg.watch),"*.torrent")
schedule2 = untied_directory, 5, 5, (cat,"stop_untied=",(cfg.watch),"*.torrent")

# Close torrents when diskspace is low
schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace,1000M))

# Move finished (no need Autotools/Automove plugin on ruTorrent)
method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="

# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="

```
