### ISSUE TITLE
AutoMove is not working 

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#87]
Hi there,

I have followed your advice from #56 to activate debug mode on Auto Tools, nevertheless, I have an issue with AutoMove and I see no error logs in it :(

The "move" from ruTorrent interface is working correcly, it's only on download complete event that it doesn't work. 

🟥  When the download is done from /downloads/temp/software --> Nothing is happening
```
[06.05.21 19:10:10] 
[06.05.21 19:10:10] AutoMove: --- begin ---
[06.05.21 19:10:10] AutoMove: --- end ---
```

🟥 When the download is done from /downloads/temp--> Nothing is happening
```
[12.05.21 15:23:46] 
[12.05.21 15:23:46] AutoMove: --- begin ---
[12.05.21 15:23:46] AutoMove: --- end ---
```

🟢 When the download is done from /downloads/complete/software --> Move is happening (even if not needed)
```
[12.05.21 15:15:55] 
[12.05.21 15:15:55] AutoMove: --- begin ---
[12.05.21 15:15:55] AutoMove: Operation Move
[12.05.21 15:15:55] AutoMove: from /downloads/complete/software/
[12.05.21 15:15:55] AutoMove: to   /downloads/complete/software/
[12.05.21 15:15:55] AutoMove: --- end ---
```

### Env File
```
TZ=Europe/Paris
PUID=1026
PGID=100

MEMORY_LIMIT=1024M
UPLOAD_MAX_SIZE=32M
OPCACHE_MEM_SIZE=256
MAX_FILE_UPLOADS=10
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

XMLRPC_AUTHBASIC_STRING=rTorrent XMLRPC restricted access
RUTORRENT_AUTHBASIC_STRING=ruTorrent restricted access
WEBDAV_AUTHBASIC_STRING=WebDAV restricted access

RT_LOG_LEVEL=info
RT_LOG_EXECUTE=false
RT_LOG_XMLRPC=false

RU_REMOVE_CORE_PLUGINS=httprpc,_cloudflare,_noty,_noty2,cookies,extratio,extsearch,feeds,filedrop,history,loginmgr,lookat,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,show_peers_like_wtorrent,spectrogram,trafic,unpack,uploadeta,xmpp
RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
RU_HTTP_TIME_OUT=30
RU_HTTP_USE_GZIP=true
RU_RPC_TIME_OUT=5
RU_LOG_RPC_CALLS=false
RU_LOG_RPC_FAULTS=true
RU_PHP_USE_GZIP=false
RU_PHP_GZIP_LEVEL=2
RU_SCHEDULE_RAND=10
RU_LOG_FILE=/data/rutorrent/rutorrent.log
RU_DO_DIAGNOSTIC=true
RU_SAVE_UPLOADED_TORRENTS=true
RU_OVERWRITE_UPLOADED_TORRENTS=false
RU_FORBID_USER_SETTINGS=false
RU_LOCALE=UTF8

RT_DHT_PORT=6840
XMLRPC_PORT=8040
RUTORRENT_PORT=33440
WEBDAV_PORT=9040
RT_INC_PORT=50040
```

### Docker Compose file
```
  rtorrent-rutorrent:
    container_name: rutorrent-main
    image: ghcr.io/crazy-max/rtorrent-rutorrent:latest
    restart: unless-stopped
    env_file:
      - /home/thelazyfox/docker/rutorrent-main/rtorrent-rutorrent.env
    volumes:
      - /home/thelazyfox/docker/rutorrent-main/data:/data
      - /mnt/media/torrents:/downloads/complete
      - /home/thelazyfox/cache/torrents:/downloads/temp
      - /home/thelazyfox/docker/rutorrent-main/data/watched:/data/watched
      - /home/thelazyfox/docker/rutorrent-main/passwd:/passwd
      - /home/thelazyfox/docker/rutorrent-main/data/tracklabels/labels:/var/www/rutorrent/plugins/tracklabels/labels:ro
      - /home/thelazyfox/docker/rutorrent-main/data/tracklabels/trackers:/var/www/rutorrent/plugins/tracklabels/trackers:ro
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: "service:vpn"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:33440/ || exit 1"]
      start_period: 15s
      interval: 5m
      timeout: 15s
      retries: 3
```
